### ISSUE TITLE
service "electric-with-postgres" can't be used with `extends` as it declare `depends_on`

### ISSUE THREAD

**Issue by AntonOfTheWoods** [electric-sql/electric#1018]
```bash
PUPPETEER_SKIP_DOWNLOAD=true npx create-electric-app@latest ntcr --template react
cd ntcr && npx electric-sql start --with-postgres

Starting ElectricSQL sync service with PostgreSQL
Docker compose config: {
  SERVICE: 'http://localhost:5133',
...
  LOGICAL_PUBLISHER_HOST: 'electric'                                                                                                                          
}                                                                                                                                                             
service "electric-with-postgres" can't be used with `extends` as it declare `depends_on`                                                                      
Failed to start the Electric backend. Check the output from 'docker compose' above. If the error message mentions a port already being allocated or address be
ing already in use, please change the configuration to an alternative port via the ELECTRIC_HTTP_PORT or ELECTRIC_PG_PROXY_PORT environment variables.

```

Looks related to https://github.com/docker/compose/issues/11544

**Comment by AntonOfTheWoods** [comment]
I can confirm that this is definitely a bug and definitely the problem. Removing the `depends` allows everything to start as expected, and the current code is illegal. It previously worked but no longer does with the most recent versions of `compose` released by Docker.

**Comment by samwillis** [comment]
@AntonOfTheWoods thanks for the report. Yep, we were using `extends` to overcome a limitation in configuring `depends_on` for different profiles. It looks like Docker have decided that that what we were doing is not valid even though it worked for us before. I've opened a PR #1025 to simplify our docker compose files with no inheritance.

**Comment by AntonOfTheWoods** [comment]
Yeah, apparently they are now actively checking for unsupported config options that used to work. Thanks for the fix!
