### ISSUE TITLE
Failed migration stuck in Electric (hosted)

### ISSUE THREAD

**Issue by lawik** [electric-sql/electric#105]
Exact details in: Electrifying SQL
https://youtube.com/live/-mCYURMoHro?feature=share

Had a hosted service electric with the todo mvc example already applied.

I wrote up a new migration with some new tables using foreign keys. Put one of them in the wrong order probably and didn't know to add the foreign key pragma.

Built the migration. No problem.
Sync the migration. Went up fine.
Checked the status if the migration. No bueno. Said Failed. No further error information. I ciuld hit Apply which did not help.

Trying the migration on a local sqlite db would probably catch it.

**Comment by icehaunter** [comment]
Whole migration story is updated, so this is no longer relevant
