### ISSUE TITLE
Fly.io deployment hangs

### ISSUE THREAD

**Issue by nukeop** [electric-sql/electric#1079]
I'm running it according to `fly.toml` from here: https://electric-sql.com/docs/deployment/fly#deploying-electric-connected-to-an-external-postgres
When I'm trying to run the sync service on fly.io, it hangs at the last step:

```
? Would you like to allocate dedicated ipv4 and ipv6 addresses now? No

This deployment will:
 * create 1 "app" machine

No machines in group app, launching a new machine
WARN failed to release lease for machine 683d607a7e4398: lease not found
-------

-------
 ✖ Failed: timeout reached waiting for health checks to pass for machine 683d607a7e4398: failed to get VM 683d607a7e4398: Get "https://api.machines.dev/v1/apps/…
-------
Error: timeout reached waiting for health checks to pass for machine 683d607a7e4398: failed to get VM 683d607a7e4398: Get "https://api.machines.dev/v1/apps/electric-sql-blahblah/machines/683d607a7e4398": net/http: request canceled
Your machine never reached the state "%s".

You can try increasing the timeout with the --wait-timeout flag
```

I left the machine parameters with the default values, 1GB of ram, shared 1x cpu. I did not change anything in `fly.toml` other than my database URL.

**Comment by KyleAMathews** [comment]
👋 we've been working the last month on a rebuild of the Electric server over at a temporary repo https://github.com/electric-sql/electric-next/

You can read more about why we made the decision at https://next.electric-sql.com/about

We're really excited about all the new possibilities the new server brings and we hope you'll check it out soon and give us your feedback.

We're now moving the temporary repo back here. As part of that migration we're closing all the old issues and PRs. We really appreciate you taking the time to investigate and report this issue!
