### ISSUE TITLE
Electrification of a table with previously dropped columns fails

### ISSUE THREAD

**Issue by alco** [electric-sql/electric#1085]
Trying to electrify a table with at least one column removed via `ALTER TABLE ... DROP COLUMN ...` fails with an error that looks like this:

```
=# ALTER TABLE foo ENABLE ELECTRIC;
ERROR:  syntax error at or near "-"
LINE 24:     "__reordered_........pg.dropped.16........" -,
                                                         ^
QUERY:  CREATE TABLE electric.shadow__public__foo (
[...]
    "__reordered_........pg.dropped.16........" -,
    "__reordered_........pg.dropped.17........" -,
[...]
    "_tag_........pg.dropped.16........" electric.tag,
    "_tag_........pg.dropped.17........" electric.tag,
[...]
)
CONTEXT:  PL/pgSQL function electric.ddlx_make_or_update_shadow_tables(text,text,oid) line 63 at EXECUTE
SQL statement "SELECT electric.ddlx_make_or_update_shadow_tables('CREATE TABLE', _schema, _oid)"
PL/pgSQL function electric.electrify(text,text) line 50 at PERFORM
SQL statement "CALL electric.electrify(table_name)"
PL/pgSQL function electric.enable(text) line 3 at CALL
```

The error is caused by the fact that the `electric.lookup_columns()` SQL function returns information about columns that have been dropped. Postgres keeps records for such columns in the `pg_attribute` system catalog but renames them to `............pg.dropped.N........` and sets their type OID to `0`.

The solution is to filter out such records when building up a column list in `electric.lookup_columns()`.

**Comment by divyenduz** [comment]
Curious, what does the release cadence look like? When is this fix available in GH releases, npm and docker hub?

**Comment by alco** [comment]
@divyenduz Correct, it's included in the `canary` image on Docker Hub as that one is built from the `main` branch on every push to it.

As for a public release, the next one is coming within the next two weeks.
