### ISSUE TITLE
Same instance of NonTransactionalDB's query() getting called with SELECTs for different tables but this._fields is the same

### ISSUE THREAD

**Issue by ondrej** [electric-sql/electric#1095]
Hello,

Simple setup here:
* Two tables, `companies` and `people`
* No FK in `companies`
* One FK in `people`: nullable column `company_id`

In React, sync is established:
```
const { synced } = await db.people.sync({
  include: { companies: true },
});
```
And query is made to return a particular person with their company (`company_id` is set):
```
db.people.liveMany({
  where: { id: { equals: 'e1407498-2eb8-4733-8d6f-96403ffc0588' } },
  include: { companies: true },
}),
```

I get the error `SyntaxError: Unexpected token 'T', "Test Company" is not valid JSON`.

Setting some breakpoints in nonTransactionalDB.js, I see NonTransactionalDB getting constructed once with `_fields` set to `people`'s fields. That same instance then has `query()` run twice:
* Once with a SELECT statement for the person with ID e1407....
* Once with a SELECT statement for their company

But because _fields is the same, `transformFields()` eventually fails — in my case because both tables have a column with the same name (`name`) but the column is a JSON in `people` and a simple string in `companies`.

**Comment by ondrej** [comment]
What may be happening. As expected:
1. Two Tables get created for each table, with their own executors created with their respective `_fields`
2. `findMany()` gets called on the `people` table with a `where` and `include` (for `companies`)
3. `findMany()` uses its own executor to call its `_findMany()` with the correct `db` (NonTransactionalDB)
4. A NonTransactionalDB gets created for `people`
5. `_findMany()` gets called with a `people`'s `db` and calls `db.query()` (table, SQL statement, db all match)
6. `db.query()`'s callback is called and we call `fetchIncludes()` with `results` (from `people`), what to include, and `people`'s db
7. `fetchIncludes()` eventually calls `fetchInclude()`, still with `people`'s `db`
8. `fetchInclude()` eventually calls `fetchRelated()`

The problem seems to be around here:
1. `fetchRelated()` looks up the other table (`companies`) and calls its `_findMany()` — but with `people`'s `db`

**Comment by ondrej** [comment]
This would repro in the ElectricSQL LinearLite example as well but it doesn't surface because a) the example never uses `include: ` and b) no 2+ tables have columns with the same name but different type.

For example, if you add:
```
include: {
  issue: true,
}
```
to Comments.tsx's `liveMany()` on line 26, and debug, the only reason `issue` will be added to `results` rows without an error is because the only two columns the two tables share is `id` and `username` — and they're both UUID and TEXT respectively.

**Comment by msfstef** [comment]
Thank you for the very detailed account and for the investigation - you are absolutely right that fields were being validated/transformed with the wrong schema when dealing with related tables.

I've opened a PR that should fix this issue https://github.com/electric-sql/electric/pull/1107
