### ISSUE TITLE
Client doesn't receive rows if those rows existed on the table prior to electrification

### ISSUE THREAD

**Issue by ondrej** [electric-sql/electric#1106]
Setup:
1. Create a simple table (no FK, etc.)
2. Add a row to the table
3. Electrify the table
4. Sync the table on the client (`const shape = await db.{table}.sync(); await shape.synced;`)
5. Query the table on the client (`const { results } = useLiveQuery(db.{table}.liveMany());`)

Expected results: `results` contains the row.

Actual results: `results` doesn't. If you modify the row in any way, it will.

Also in Discord https://discordapp.com/channels/933657521581858818/1221983203812835328

**Comment by alco** [comment]
@ondrej Thanks for the report.

We've identified the root cause of the bug and are working on a fix.
