### ISSUE TITLE
Replication suspended

### ISSUE THREAD

**Issue by andrezimpel** [electric-sql/electric#1155]
In my server logs I can the message "Outgoing replication to the client is suspended because there are 30 unacked transactions" constantly. Also changes stoped syncing across clients. I don't really know how to track the issue down or to give more context right now. Help is appreciated a lot!

**Comment by andrezimpel** [comment]
Resetting or switching to a new database locally solves it but if a client has unsynced changes they obviously get lost. :/

**Comment by alco** [comment]
Hey @andrezimpel . Which versions of the client and the server are you using?

Could you enable debug logging on the client and share the log output from the browser console leading up to the moment when replication gets suspended? Thanks!

**Comment by KyleAMathews** [comment]
👋 we've been working the last month on a rebuild of the Electric server over at a temporary repo https://github.com/electric-sql/electric-next/

You can read more about why we made the decision at https://next.electric-sql.com/about

We're really excited about all the new possibilities the new server brings and we hope you'll check it out soon and give us your feedback.

We're now moving the temporary repo back here. As part of that migration we're closing all the old issues and PRs. We really appreciate you taking the time to investigate and report this issue!
