### ISSUE TITLE
[Question] Sync partial results

### ISSUE THREAD

**Issue by MichalNemec** [electric-sql/electric#1176]
Hello, what is the status of paginated results in sync?
I have messages that belong to a room.
i would need sync last 5 messages per room.

I cant seem to find how to do this.
Is there something im missing or is this not implemented yet? If not implemented, what would be the timeframe?

Thank you!

**Comment by KyleAMathews** [comment]
👋 we've been working the last month on a rebuild of the Electric server over at a temporary repo https://github.com/electric-sql/electric-next/

You can read more about why we made the decision at https://next.electric-sql.com/about

We're really excited about all the new possibilities the new server brings and we hope you'll check it out soon and give us your feedback.

We're now moving the temporary repo back here. As part of that migration we're closing all the old issues and PRs. We really appreciate you taking the time to investigate and report this issue!
