### ISSUE TITLE
Geo data support

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [electric-sql/electric#1227]
Hi does electric  sql support geo data, I am currently looking into [PostgreSQL](http://www.postgresql.org/) + [PostGIS](http://postgis.refractions.net/) but I am unsure if the SQLlite supports the geo data I did find a fork of SQLlite that seems to support geo data

https://www.gaia-gis.it/fossil/libspatialite/index

**Comment by samwillis** [comment]
Hey @Ashraf-Ali-aa 

we don't support geo data type support yet, but very much plan to. If you let us know the use case there are some work arounds that you could use at the moment though.

If you are looking for full postgis support on the client we are planning to make it available as an extension to [PGlite](https://github.com/electric-sql/pglite) (a WASM build of Postgres we're building). Electric support for PGlite is imminent (ETA early next week), and Postgres extension support for PGlite is being actively worked on. We hope to have it working in the next few months.

**Comment by Ashraf-Ali-aa** [comment]
thanks for the update, I wanted a way to query location data while offline, I was planning on storing the data in geojson format, but if you are planning on adding PostGIS to [PGlite](https://github.com/electric-sql/pglite) this would be brilliant.

**Comment by Ashraf-Ali-aa** [comment]
Also would PGlite support react native?

**Comment by KyleAMathews** [comment]
👋 we've been working the last month on a rebuild of the Electric server over at a temporary repo https://github.com/electric-sql/electric-next/

You can read more about why we made the decision at https://next.electric-sql.com/about

We're really excited about all the new possibilities the new server brings and we hope you'll check it out soon and give us your feedback.

We're now moving the temporary repo back here. As part of that migration we're closing all the old issues and PRs. We really appreciate you taking the time to investigate and report this issue!
