### ISSUE TITLE
Upgrade electricsql from 0.10.1 to 0.11.1, can't connect to electric proxy service

### ISSUE THREAD

**Issue by thunderfalco** [electric-sql/electric#1243]
I upgrade electricsql from 0.10.1 to 0.11.1,but 403, when I use 0.10.1, everthing is ok, but in 0.11.1

![image](https://uploads.linear.app/0467b297-8a55-4fc0-82da-624730a09e44/e5e80964-d047-4b90-8754-ba949bbfcfbe/ddc2a821-ea60-4e24-a323-7250096b6030?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzA0NjdiMjk3LThhNTUtNGZjMC04MmRhLTYyNDczMGEwOWU0NC9lNWU4MDk2NC1kMDQ3LTRiOTAtODc1NC1iYTk0OWJiZmNmYmUvZGRjMmE4MjEtZWE2MC00ZTI0LWEzMjMtNzI1MDA5NmI2MDMwIiwiaWF0IjoxNzE1ODQ3MDA2LCJleHAiOjMzMjg2NDA3MDA2fQ.452dMzevhSCn79WNzmhu7QGMPz7zVKDeJQg36CUkjK8 "=731x")

**Comment by samwillis** [comment]
Hey @thunderfalco 

One reason that error would happen Is if the sync server is still running v0.10. Did you start electric with 'npx electric-sql start'? If you did it should have pulled the latest image, but if you are running Electric directly with Docker you may need to pull the latest image yourself with the Docker cli or gui.

If you do have the server on v0.11 could you post its logs after trying to generate a client?

**Comment by KyleAMathews** [comment]
👋 we've been working the last month on a rebuild of the Electric server over at a temporary repo https://github.com/electric-sql/electric-next/

You can read more about why we made the decision at https://next.electric-sql.com/about

We're really excited about all the new possibilities the new server brings and we hope you'll check it out soon and give us your feedback.

We're now moving the temporary repo back here. As part of that migration we're closing all the old issues and PRs. We really appreciate you taking the time to investigate and report this issue!
