### ISSUE TITLE
Improve client generation failure messages at the client level

### ISSUE THREAD

**Issue by AntonOfTheWoods** [electric-sql/electric#1253]
In certain circumstances where the reason is clearly known (e.g., trying to generate the client when there are tables that have FKs to unelectrified tables) the current message at the client level is:

```
...
Error: Error in connector: Error querying the database: Error querying the database: The server terminated the connection.
...
```

It would be a much nicer DX to have the message, which is clearly visible in the electric server logs, returned to the client so the developer can see without going looking for logs elsewhere.

**Comment by KyleAMathews** [comment]
👋 we've been working the last month on a rebuild of the Electric server over at a temporary repo https://github.com/electric-sql/electric-next/

You can read more about why we made the decision at https://next.electric-sql.com/about

We're really excited about all the new possibilities the new server brings and we hope you'll check it out soon and give us your feedback.

We're now moving the temporary repo back here. As part of that migration we're closing all the old issues and PRs. We really appreciate you taking the time to investigate and report this issue!
