### ISSUE TITLE
Possible issue in the new ShapeManager code.

### ISSUE THREAD

**Issue by davidmartos96** [electric-sql/electric#1283]
cc @msfstef 

While porting the new ShapeManager refactor to Dart we found an issue that we are unsure if it could cause unexpected problems.

https://github.com/electric-sql/electric/blob/276149df52dab1b20cf848ae8ba926651c026d53/clients/typescript/src/satellite/shapes/shapeManager.ts#L331

The following line is accessing the promise resolver unconditionally, but it can be undefined. It currently throws, but the exception is not bubbled up because of the `Promise.allSettled` in the `AsyncEventEmitter`.

In fact, one of the tests reaches this situation, the one named: `a subscription that failed to apply because of FK constraint triggers GC`

**Comment by msfstef** [comment]
Thanks for reporting this! Indeed we had noticed that the `AsyncEventEmitter` was suppressing errors and we had a PR open to fix that (see https://github.com/electric-sql/electric/pull/1247).

While working on that PR I managed to reproduce this error, you can see a description of what was happening here: https://github.com/electric-sql/electric/pull/1247#discussion_r1608478725

The above PR should also resolve this issue once merged.

**Comment by davidmartos96** [comment]
@msfstef I see, thanks!
We encountered this hidden error really by chance, as our Dart implementation wasn't doing the equivalent of Promise.waitSettled.
