### ISSUE TITLE
Demo example with PostGis plugin??

### ISSUE THREAD

**Issue by roger120981** [electric-sql/electric#1297]
Hello, I would like to know if possible replicate postgis geometries with electric,  if yes, a demo for the learning process it' would be great, thanks

**Comment by KyleAMathews** [comment]
👋 we've been working the last month on a rebuild of the Electric server over at a temporary repo https://github.com/electric-sql/electric-next/

You can read more about why we made the decision at https://next.electric-sql.com/about

We're really excited about all the new possibilities the new server brings and we hope you'll check it out soon and give us your feedback.

We're now moving the temporary repo back here. As part of that migration we're closing all the old issues and PRs. We really appreciate you taking the time to investigate and report this issue!

**Comment by andre-brandao** [comment]
any updates on this topic?
