### ISSUE TITLE
Unable to install electric-sql on MacOS & Node@22

### ISSUE THREAD

**Issue by WailRoth** [electric-sql/electric#1301]
`Computer specs`
```
OS: MacOS 14.2.1 (23C71)
Node: 22.0
```

`error`
```
./src/util/macros.lzz:150:35: error: no matching member function for call to 'SetAccessor'
│         recv->InstanceTemplate()->SetAccessor(
│         ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
│ /Users/XXX/Library/Caches/node-gyp/22.0.0/include/node/v8-template.h:1049:8: note: candidate function not viable: no known conversion from 'v8::AccessControl' to 'v8::PropertyAttribute' for 5th argument
│   void SetAccessor(
│        ^
│ /Users/xxx/Library/Caches/node-gyp/22.0.0/include/node/v8-template.h:1055:8: note: candidate function not viable: no known conversion from 'v8::AccessorGetterCallback' (aka 'void (*)(Local<v8::String>, cons…
│   void SetAccessor(
│        ^
│ ./src/objects/database.lzz:180:21: warning: variable 'status' set but not used [-Wunused-but-set-variable]
│                 int status = sqlite3_db_config(db_handle, SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION, 1, NULL);
│                     ^
│ 1 warning and 1 error generated.
│ make: *** [Release/obj.target/better_sqlite3/src/better_sqlite3.o] Error 1
```

So has you can see, (or not with the error), it tries to run the `better-sql3` installation script,  `node_modules/.pnpm/better-sqlite3@8.7.0/node_modules/better-sqlite3`

from https://github.com/electric-sql/electric/blob/main/pnpm-lock.yaml
```
better-sqlite3:
 specifier: ^8.4.0
 version: 8.7.0
```

But, this version is not supported with node@22

**Comment by WailRoth** [comment]
For those who want to downgrade to node@20 on macos:
https://apple.stackexchange.com/questions/171530/how-do-i-downgrade-node-or-install-a-specific-previous-version-using-homebrew

**Comment by msfstef** [comment]
It seems like the better-sqlite3 version currently used does not support Node v22, I've opened a PR to upgrade the dependency (which comes at the cost of dropping Node v16 support, but that's at its EOL) https://github.com/electric-sql/electric/pull/1378

Thank you for raising the issue!
