### ISSUE TITLE
Zod rejects UUIDs that Postgres deems valid

### ISSUE THREAD

**Issue by alco** [electric-sql/electric#1302]
_Originally reported by @fooware [in Discord](https://discord.com/channels/933657521581858818/933657523049885698/1245097379024208003)_

Turns out that Postgres will accept a truly random UUID, but Zod will reject it if it doesn't have the `version` nibble and possibly also the `variant` bits set correctly.

The end result is that if such an "invalid" UUID is entered into the database from a system that doesn't validate the input with Zod, Electric sync will permanently die on all clients until the offending row is removed.

You don't get any good errors or anything either indicating the underlying problem:
![screenshot1](https://github.com/electric-sql/electric/assets/207748/0cbd2fa0-a78a-46ac-aa91-a4770ed7b665)
![screenshot2](https://github.com/electric-sql/electric/assets/207748/f59e5eb3-d9e4-475b-bbba-2c406ef545b6)

I mean, it is _technically_ correct, but having stricter UUID checks in Electric vs Postgres is a bomb waiting to happen at the worst possible time in production, IMHO.

Related issue / discussion at Zod:
https://github.com/colinhacks/zod/issues/2122 

---

To get an example to test, simply generate a valid V4 UUID, like this one:
```
76e1760a-d17a-41cd-9453-d8a9d6c994e0 
```

Then replace the -4 (version 4) with for example -f (not a valid version) like so:
```
76e1760a-d17a-f1cd-9453-d8a9d6c994e0 
```

Postgres will accept this "UUID" just fine as for example a primary key, but Zod and Electric will throw an error trying to read it from the DB.

**Comment by James3UK** [comment]
Curly braces around UUID's are very common in Microsoft applications also referred to as GUIDs it would be great if these could also be validated, maybe a separate GUID validator or some options?

PostgreSQL also accepts the following alternative forms for input: use of upper-case digits, the standard format surrounded by braces, omitting some or all hyphens, adding a hyphen after any group of four digits. Examples are:

A0EEBC99-9C0B-4EF8-BB6D-6BB9BD380A11
{a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11}
a0eebc999c0b4ef8bb6d6bb9bd380a11
a0ee-bc99-9c0b-4ef8-bb6d-6bb9-bd38-0a11
{a0eebc99-9c0b4ef8-bb6d6bb9-bd380a11}

https://www.postgresql.org/docs/current/datatype-uuid.html

**Comment by KyleAMathews** [comment]
👋 we've been working the last month on a rebuild of the Electric server over at a temporary repo https://github.com/electric-sql/electric-next/

You can read more about why we made the decision at https://next.electric-sql.com/about

We're really excited about all the new possibilities the new server brings and we hope you'll check it out soon and give us your feedback.

We're now moving the temporary repo back here. As part of that migration we're closing all the old issues and PRs. We really appreciate you taking the time to investigate and report this issue!
