### ISSUE TITLE
Possible issues on the Typescript client

### ISSUE THREAD

**Issue by js2702** [electric-sql/electric#132]
We've been developing (@davidmartos96) a Dart implementation of the electric client (Available here https://github.com/SkillDevs/electric_dart). We found some issues/ had some concerns and some questions from the client implementation. We will post them all here in different sections, you can later organize them as you wish, or discard them.

# Issues

## Electric tables sqlite types
Some metadata tables that Electric creates (oplogTable, metaTable, etc) use the column type STRING. Which does not exist. 
The affinity for the column defaults as numeric. We had some issues here where we encountered a number instead of a string. 
This works in Typescript but might be a source of problems in the future. 

Here is an example: https://github.com/electric-sql/electric/blob/a52c752236699d8dfb289cbb10f5a15b9bf2c9b8/clients/typescript/src/migrators/schema.ts#L20

## Union return types
Some functions in the satellite client and process have a return type of `Promise<void | Error>` or `Promise<void | SatelliteError>`. This is fine but we found some places where the promise is rejected instead of returning the Error. It may be confusing to have a header which returns an union type and the promise actually fails. 

The implementation method.
https://github.com/electric-sql/electric/blob/a52c752236699d8dfb289cbb10f5a15b9bf2c9b8/clients/typescript/src/satellite/client.ts#L239

The interface method.
https://github.com/electric-sql/electric/blob/a52c752236699d8dfb289cbb10f5a15b9bf2c9b8/clients/typescript/src/satellite/index.ts#L60

## Unused property
https://github.com/electric-sql/electric/blob/a52c752236699d8dfb289cbb10f5a15b9bf2c9b8/clients/typescript/src/satellite/process.ts#L71

## Throttle cleanup
The following lodash throttled never gets cleaned up. The output of throttle has a method cancel.
https://github.com/electric-sql/electric/blob/a52c752236699d8dfb289cbb10f5a15b9bf2c9b8/clients/typescript/src/satellite/process.ts#L113
Maybe it could be instantiated in the start and cleaned up in stop?

## Connectivity change subscription cleanup
This subscription never gets unsubscribed, maybe it could be unsubscribe right before subscribing again?
https://github.com/electric-sql/electric/blob/a52c752236699d8dfb289cbb10f5a15b9bf2c9b8/clients/typescript/src/satellite/process.ts#L150

## Typo?
This probably should be refreshToken.
https://github.com/electric-sql/electric/blob/a52c752236699d8dfb289cbb10f5a15b9bf2c9b8/clients/typescript/src/satellite/process.ts#L282

## Untyped tests
There are some tests which we had some questions while replicating. Mainly because they were not typed. Mostly working with `any`.  One example is the test 'apply empty incoming'.

https://github.com/electric-sql/electric/blob/a52c752236699d8dfb289cbb10f5a15b9bf2c9b8/clients/typescript/test/satellite/process.test.ts#L525
Here this function has 3 parameters, but the second and the third don't allow undefined. Are undefined values in this function supposed to exist in a real usage case?

Also, in 'compensations: using triggers with flag ' There are no expectations, just a single `t.true(true)`. 

In: 
https://github.com/electric-sql/electric/blob/a52c752236699d8dfb289cbb10f5a15b9bf2c9b8/clients/typescript/test/satellite/process.test.ts#L1075

This test is actually failing silently. When the setTimeout resolves the test already finished so even though the expectation is failing it doesn't throw. If we update:

```ts
 // OLD
setTimeout(async () => {
  const lsn2 = await satellite._getMeta('lastSentRowId')
  t.is(lsn2, '2')
}, 200)

// NEW
await sleepAsync(200)
const lsn2 = await satellite._getMeta('lastSentRowId')
t.is(lsn2, '2') // This now fails

```
It actually fails.

# Questions

1. Here it is assumed that `secondValue` is not undefined. But it has not been checked. Is that correct? 
https://github.com/electric-sql/electric/blob/a52c752236699d8dfb289cbb10f5a15b9bf2c9b8/clients/typescript/src/satellite/merge.ts#L31

2. Would it be possible to have the Docker images and the Electric web client updated to the protocol 1.x? Currently the version in npm is 0.4.3, which uses the electric protocol 0.2. It would be nice to have a version upgrade so that the Flutter Dart client can easily be tested without manually building the web client. 

3. There seems to be an issue when deleting an updated entry. We found this using the todoMVC example. It seems to be replicable on the web client. Steps to reproduce:

- Create a TODO.
- Mark it as done.
- Delete this todo. (It will reappear instantly)
- Delete this todo. (Now it works)

What happens sometimes is that right after deleting the TODO it appears again marked as done.
Maybe related to this. When a new client appears and it replicates from the empty state. Some todos will appear even though they were deleted. We think these could be the same TODOs that showed the previous bug.

**Comment by thruflo** [comment]
Hi @js2702, thanks for this. Really appreciate the feedback. We’ll look through and come back to you on both issues and questions.
