### ISSUE TITLE
Issue with ElectricSQL when I try to change the content of an entry in the database

### ISSUE THREAD

**Issue by SukiTUK** [electric-sql/electric#1321]
Hello Team,

The file I am trying to execute is https://github.com/SukiTUK/SpreadsheetWithElectric/blob/main/my-app/src/Example.tsx#L294
-> function handlecellblur

To start the app > 
1. run electric server "npx electric-sql start --with-postgres"
2. Goto my-app folder and run "npm run dev"

Steps to reproduce: In the application, 
1. add a row.
2. add a column.
3. enter a content in the cell and click anywhere outside to trigger the write to the database.
**Result:** There is an entry created in the database contentmap
4. Again change the content of the same cell and click anywhere outside to trigger the write to the database.
**Result:** There is the following error on the console.

> Uncaught (in promise) ZodError
    at get error (index.mjs:537:31)
    at _ZodObject.parse (index.mjs:636:22)
    at validate (validation.ts:15:31)
    at Table._update (table.ts:1314:34)
    at table.ts:354:12
    at executor.ts:49:7
    at Promise.catch._run.sql (adapter.ts:67:7)
    at new Promise (<anonymous>)
    at DatabaseAdapter2.transaction (adapter.ts:58:12)
    at async Executor.transaction (executor.ts:48:13)

Could you please help me with this issue?

**Comment by stildalf** [comment]
Hey @SukiTUK, we can't see your code sample, it's in a private repo.

**Comment by SukiTUK** [comment]
> Hey @SukiTUK, we can't see your code sample, it's in a private repo.

@stildalf  I have made the repository public. Could you check?

**Comment by msfstef** [comment]
@SukiTUK issue has been addressed in [the Discord help and support channel](https://discord.com/channels/933657521581858818/1246479416343793734/1250755945089339413).

Problem seems to be that your schema uses composite PK that includes FK columns that also have update cascades on them, and Electric requires [immutable primary keys](https://electric-sql.com/docs/reference/roadmap#primary-keys-are-immutable).

You can read @alco's and @samwillis' replies for more details in the thread. Hope this covers the question!

**Comment by KyleAMathews** [comment]
👋 we've been working the last month on a rebuild of the Electric server over at a temporary repo https://github.com/electric-sql/electric-next/

You can read more about why we made the decision at https://next.electric-sql.com/about

We're really excited about all the new possibilities the new server brings and we hope you'll check it out soon and give us your feedback.

We're now moving the temporary repo back here. As part of that migration we're closing all the old issues and PRs. We really appreciate you taking the time to investigate and report this issue!
