### ISSUE TITLE
tauri-sqlite example start failed 

### ISSUE THREAD

**Issue by thunderfalco** [electric-sql/electric#1325]
when start tauri-sqlite example,  "const conn = await createDatabase(scopedDbName);
" throw exception: "error returned from database: (code: 5) database is locked"

**Comment by thunderfalco** [comment]
Additionally, when createDatebase  'Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'window.__TAURI_INTERNALS__.invoke')' appeared

**Comment by thunderfalco** [comment]
previous error had sovled, but now useElectric() always undefined

**Comment by KyleAMathews** [comment]
👋 we've been working the last month on a rebuild of the Electric server over at a temporary repo https://github.com/electric-sql/electric-next/

You can read more about why we made the decision at https://next.electric-sql.com/about

We're really excited about all the new possibilities the new server brings and we hope you'll check it out soon and give us your feedback.

We're now moving the temporary repo back here. As part of that migration we're closing all the old issues and PRs. We really appreciate you taking the time to investigate and report this issue!
