### ISSUE TITLE
Secure auth invalid key

### ISSUE THREAD

**Issue by rgarcia** [electric-sql/electric#1328]
Trying to get started with Electric and having a bad time... following the directions for generating a JWT key [here](https://electric-sql.com/docs/usage/auth/secure) and it doesn't seem to work. Repro:

```bash
openssl ecparam -name prime256v1 -genkey | openssl pkcs8 -topk8 -nocrypt -out private_key.pem
openssl ec -in private_key.pem -pubout -out public_key.pem
cat << EOF > env-file
AUTH_MODE=secure
AUTH_JWT_KEY=$(cat public_key.pem | base64)
AUTH_JWT_KEY_IS_BASE64_ENCODED=true
AUTH_JWT_ALG=ES256
DATABASE_REQUIRE_SSL=true
DATABASE_URL=<redacted>
ELECTRIC_WRITE_TO_PG_MODE=direct_writes
PG_PROXY_PASSWORD=<redacted>
EOF
docker run --env-file env-file -it electricsql/electric
```

Output: 

```
▓ ┌───────────────────────┐
▓ │  CONFIGURATION ERROR  │
▓ ┕━━━━━━━━━━━━━━━━━━━━━━━┙
▓ 
▓ The following required configuration options have invalid or missing values:
▓ 
▓   * AUTH_JWT_KEY is not a valid key for AUTH_JWT_ALG=ES256 or it has invalid format.
▓ 
▓     The key for RS* and ES* algorithms must use the PEM format, with the header
▓     and footer included:
▓ 
▓         -----BEGIN PUBLIC KEY-----
▓         MFkwEwYHKoZIzj0CAQY...
▓         ...
▓         -----END PUBLIC KEY-----
▓ 
▓ Please review the official configuration reference at
▓ https://electric-sql.com/docs/api/service
▓ and double-check your values.
```

Would appreciate any help!

**Comment by alco** [comment]
Hey @rgarcia. I think the problem is that `base64` wraps its output to multiple lines and only the first line gets assigned to the `AUTH_JWT_KEY` variable.

Here's the contents of the `env-file` I get after executing your code snippet:
```
$ cat env-file 
AUTH_MODE=secure
AUTH_JWT_KEY=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFR
Y0RRZ0FFaDJpZXk1cElkMGRVclZoM2Y2OWF3a0xEallVdApvWVVwK3FCNjMvM0Z2dVhzVHZLUEdo
MkZQajNkQmJ3YU9VeE9zcXVoSFVrbDVwaDZ6eVhFcjdSSzJBPT0KLS0tLS1FTkQgUFVCTElDIEtF
WS0tLS0tCg==
AUTH_JWT_KEY_IS_BASE64_ENCODED=true
AUTH_JWT_ALG=ES256
DATABASE_REQUIRE_SSL=true
DATABASE_URL=<redacted>
ELECTRIC_WRITE_TO_PG_MODE=direct_writes
```

You can see how that results in the `AUTH_JWT_KEY` getting a value inside the Docker container that's different from what you'd expect:
```
$ docker run --rm --env-file env-file busybox env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=22249ac03604
AUTH_MODE=secure
AUTH_JWT_KEY=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFR
WS0tLS0tCg==
AUTH_JWT_KEY_IS_BASE64_ENCODED=true
AUTH_JWT_ALG=ES256
DATABASE_REQUIRE_SSL=true
DATABASE_URL=<redacted>
ELECTRIC_WRITE_TO_PG_MODE=direct_writes
PG_PROXY_PASSWORD=<redacted>
HOME=/root

$ docker run --rm -it --env-file env-file busybox
/ # echo $AUTH_JWT_KEY
LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFR
```

Add the `-w 0` flag to your invocation of `base64`:
```
AUTH_JWT_KEY=$(cat public_key.pem | base64 -w 0)
```

That should fix it.

**Comment by rgarcia** [comment]
I'm on mac os and base64 doesn't appear to wrap by default (it doesn't have a `-w 0` flag either). When I inspect env-file the base64 encoded public key looks correct (one line):

```
AUTH_JWT_KEY=LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ2I1alVKVUhmWHNSU2tEN2QKQUZvcWxKeWU5NExRTVV0YjRSeGJ4SGdXaE5HaFJBTkNBQVQxdkdOSU1VZFZGU0IxT0NqQllQYnluWThaQmxGTQoyV2MrOVdjRmR1VXJTY2lFdEpEOGdIWHVUdXdkelRtWTVJNHlFK01WanVORlR4VHNXcC9ZRE5hQwotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
```

**Comment by alco** [comment]
Ah, right. The `AUTH_JWT_KEY_IS_BASE64_ENCODED` option only applies to symmetric keys, i.e. when `AUTH_JWT_ALG=HS*`.

An asymmetric public key needs to be used verbatim. Unfortunately, env files do not support multi-line strings, so you'd need to pass the key some other way.

One possibility is to set `AUTH_JWT_KEY` in the shell where you invoke `docker run` and then pass it to Docker via the `-e` flag, like so:
```
$ export AUTH_JWT_KEY="$(cat public_key.pem)"
$ docker run --env-file env-file -e AUTH_JWT_KEY -it electricsql/electric
```

**Comment by rgarcia** [comment]
ahh ok... the shell repro is mainly a repro of how my infra provider does things, but I was able to figure out how to get multiline env vars in my infra provider and so I'm all set.

Since multiline env vars are a common source of headaches it'd be nice if `AUTH_JWT_KEY_IS_BASE64_ENCODED` was supported for all key types.

Thanks for the help!

**Comment by alco** [comment]
I think we will adjust the behaviour of that env var to apply to all key types. Thanks for your input!
