### ISSUE TITLE
Checkout and Linear example not working (client side issue)

### ISSUE THREAD

**Issue by MatteoGauthier** [electric-sql/electric#1333]
Hey ! I got an issue while testing Electric from the docs:

1. Open https://checkout-demo.electric-sql.com/ on desktrop
2. Open https://checkout-demo.electric-sql.com/ on mobile
3. Desktop got to account
4. Mobile make a purchase
5. CRASH On desktop
![Capture d’écran 2024-06-06 à 14 28 14](https://github.com/electric-sql/electric/assets/32040951/ab375afb-59a2-4725-bf87-41a554329f4e)

I got a similar issue (not the same cause for sure)

On https://linear-lite-pg.electric-sql.com/board

![Capture d’écran 2024-06-06 à 14 31 59](https://github.com/electric-sql/electric/assets/32040951/38056166-b1ae-43c5-a399-3b9050e6f237)

**Comment by msfstef** [comment]
hey @MatteoGauthier, thank you for reporting this!

If you clear the application data (on Chrome it's Dev Tools -> Application tab -> Clear site data with IndexedDB ticked) on your desktop, does the issue still persist? I cannot reproduce your issue and want to make sure it's not a transient bug
