### ISSUE TITLE
Sync service complains about multiple connections from the same client

### ISSUE THREAD

**Issue by alco** [electric-sql/electric#1335]
Multiple people have reported this happen for different reasons.

Here's one such report:

When using the Dart client, after the app closes and Electric considers the client disconnected because of not responding to the ping, Electric will complain about multiple connections from the same client.
How is that possible? Maybe the service is not clearing the client_id connection that was closed due to the unresponded ping?

```
-- App disconnects, without gracefully closing the socket connection --
-- After a while, the server disconnects the client --

electric-1  | 16:00:17.172 pid=<0.4058.0> client_id=8c120869-9cc5-43cb-b8bb-c042e747e07a instance_id=4f15a93c-91b1-4f99-98da-3e916829b330 user_id=6bdd56fa-acd7-4349-8de8-7735859494bf [info] Client is not responding to ping, disconnecting

-- User reopens the app and reconnects --

electric-1  | 16:00:26.029 pid=<0.4063.0> [info] GET /ws
electric-1  | 16:00:26.030 pid=<0.4063.0> instance_id=4f15a93c-91b1-4f99-98da-3e916829b330 [info] Sent 101 in 343µs
electric-1  | 16:00:27.351 pid=<0.4063.0> client_id=8c120869-9cc5-43cb-b8bb-c042e747e07a instance_id=4f15a93c-91b1-4f99-98da-3e916829b330 [info] attempted multiple connections from the same client
```
 
Issue report on the Dart client with full client and server logs: https://github.com/SkillDevs/electric_dart/issues/23

**Comment by KyleAMathews** [comment]
👋 we've been working the last month on a rebuild of the Electric server over at a temporary repo https://github.com/electric-sql/electric-next/

You can read more about why we made the decision at https://next.electric-sql.com/about

We're really excited about all the new possibilities the new server brings and we hope you'll check it out soon and give us your feedback.

We're now moving the temporary repo back here. As part of that migration we're closing all the old issues and PRs. We really appreciate you taking the time to investigate and report this issue!
