### ISSUE TITLE
Pre-built  Linearlite for tauri-postgres example not working

### ISSUE THREAD

**Issue by recurser** [electric-sql/electric#1366]
I'm trying to run the Linearlite app [linked to](https://electric-sql-local-ai-demo-download.s3.amazonaws.com/Linearlite_0.1.0_aarch64_20240205_01.dmg) from your article [Local AI with Postgres, pgvector and llama2](https://electric-sql.com/blog/2024/02/05/local-first-ai-with-tauri-postgres-pgvector-llama).

The app hangs while `Loading Workspace`. The inspector shows that it can't connect to the backend, which has presumably been taken down:

`WebSocket connection to 'ws://backend.tauri-demo.electric-sql.com/ws' failed: A server with the specified hostname could not be found.`

<img width="937" alt="Screenshot 2024-06-14 at 11 54 25" src="https://github.com/electric-sql/electric/assets/96322/144c7750-4721-4aae-a43f-55bdc94cbb35">

**Comment by johnmcdowall** [comment]
@KyleAMathews Where is the code that used to be here for the tauri / electric-sql example that was shown in the Feb 24th 2024 blog post?

**Comment by KyleAMathews** [comment]
In the archived repo https://github.com/electric-sql/electric-old

**Comment by johnmcdowall** [comment]
@KyleAMathews Thanks, but I already looked there. The examples folder does not contain the `linearlite-tauri` folder, just some super bare bones `tauri-sqlite` folder.

**Comment by alco** [comment]
@johnmcdowall I have recovered these two branches in the old repo. Can you see if any of them are what you're looking for?
- [`garry/tauri-example-postgres`](https://github.com/electric-sql/electric-old/compare/main...garry/tauri-example-postgres)
- [`samwillis/linearlite-tauri`](https://github.com/electric-sql/electric-old/compare/main...samwillis/linearlite-tauri)

**Comment by johnmcdowall** [comment]
@alco Thanks for digging those up. I see now that they are less relevant given the new direction.
