### ISSUE TITLE
Incoming protobuf message size

### ISSUE THREAD

**Issue by davidmartos96** [electric-sql/electric#1372]
While benchmarking the Dart client we noticed that the protobuf library in Dart will complain when trying to decode a message bigger than 64 MB. 
One way this can happen is if the initial sync is very large, because everything seems to be bundled in a single SatOpLog. 
Would it make sense to split the incoming SatOpLogs in multiple ones? Unfortunately this 64 MB limit per message is not something Google plans to change.

**Comment by KyleAMathews** [comment]
👋 we've been working the last month on a rebuild of the Electric server over at a temporary repo https://github.com/electric-sql/electric-next/

You can read more about why we made the decision at https://next.electric-sql.com/about

We're really excited about all the new possibilities the new server brings and we hope you'll check it out soon and give us your feedback.

We're now moving the temporary repo back here. As part of that migration we're closing all the old issues and PRs. We really appreciate you taking the time to investigate and report this issue!
