### ISSUE TITLE
Integrated with VTable

### ISSUE THREAD

**Issue by fangsmile** [electric-sql/electric#1373]
Whether it can be integrated with VTable. VTable table library has a strong visual display ability and high-performance.
You can check the VTable website for more information：https://visactor.io/vtable
Github: https://github.com/VisActor/VTable
![img_v3_029n_c20f8bf0-914d-480e-9369-9541ff50bc7g](https://github.com/electric-sql/electric/assets/3468473/93b40403-027d-4412-9410-7a26f6be2af3)

**Comment by fangsmile** [comment]
Does that mean we'll be able to use it later ?

**Comment by msfstef** [comment]
@fangsmile I'm not sure what you mean by "able to use it later"? I believe it's possible to set up a VTable in the way that is described for the async lazy data loading example, with the data being loaded from the local DB using Electric, so it should be implementable with the current state of the library.

**Comment by fangsmile** [comment]
![image](https://github.com/electric-sql/electric/assets/3468473/0d4f19b1-193e-42ad-8463-c52db5be609f)
Whether the table library referenced here can be replaced with VTable.  Or could i contribute code to complete the replacement？

**Comment by msfstef** [comment]
@fangsmile we generally accept contributions but is there a particular reason to prefer VTable over the Glide Data Grid? Have you found issues with the current toolbar table implementation?

**Comment by KyleAMathews** [comment]
👋 we've been working the last month on a rebuild of the Electric server over at a temporary repo https://github.com/electric-sql/electric-next/

You can read more about why we made the decision at https://next.electric-sql.com/about

We're really excited about all the new possibilities the new server brings and we hope you'll check it out soon and give us your feedback.

We're now moving the temporary repo back here. As part of that migration we're closing all the old issues and PRs. We really appreciate you taking the time to investigate and report this issue!
