### ISSUE TITLE
Typos in two values of the SatErrorResp.ErrorCode enum

### ISSUE THREAD

**Issue by alco** [electric-sql/electric#138]
Note the same typo in two instances of `MISSMATCH` below
https://github.com/electric-sql/electric/blob/b2e7ab6d74def0bb0dbbaa990d4612a21241b5fa/protocol/satellite.proto#L85-L93

Fixing them in a backwards-compatible way should be as simple as
```diff
 enum ErrorCode {
+    option allow_alias = true;
     INTERNAL = 0;
     AUTH_REQUIRED = 1;
     AUTH_FAILED = 2;
     REPLICATION_FAILED = 3;
     INVALID_REQUEST = 4;
+    PROTO_VSN_MISMATCH = 5;
     PROTO_VSN_MISSMATCH = 5;
+    SCHEMA_VSN_MISMATCH = 6;
     SCHEMA_VSN_MISSMATCH = 6;
 }
```

**Comment by icehaunter** [comment]
Closed in https://github.com/electric-sql/electric/pull/257
