### ISSUE TITLE
Boolean CLI options all seem to default to false 

### ISSUE THREAD

**Issue by alco** [electric-sql/electric#1404]
Both `DATABASE_USE_IPV6` and `ELECTRIC_USE_IPV6` have `true` as their default value:
https://github.com/electric-sql/electric/blob/af6a7be7b6d89bdd82cc17ebb12f7d446da59096/components/cli/src/config-options.ts#L166-L178

However, when I start Electric with `npm run electric:start` inside a starter app, the printed config shows `false` for all boolean options:
```
Starting ElectricSQL sync service
Docker compose config:
{
[...]
  WITH_POSTGRES: 'false',
[...]
  DATABASE_REQUIRE_SSL: 'false',
  DATABASE_USE_IPV6: 'false',
  ELECTRIC_USE_IPV6: 'false',
[...]
```

**Comment by msfstef** [comment]
Addressed in https://github.com/electric-sql/electric/pull/1405
