### ISSUE TITLE
Initialization Error Using Supabase

### ISSUE THREAD

**Issue by e-lobo** [electric-sql/electric#1421]
```
 Failed to start child Electric.Replication.PostgresConnectorMng:
▓   {{:case_clause, :undefined}, [{Electric.Replication.PostgresConnectorMng, :get_verify_peer_opts, 0, [file: ~c"lib/electric/replication/postgres_manager.ex", line: 358]}, {Electric.Replication.PostgresConnectorMng, :maybe_verify_peer, 1, [file: ~c"lib/electric/replication/postgres_manager.ex", line: 350]}, {Keyword, :update!, 4, [file: ~c"lib/keyword.ex", line: 1144]}, {Keyword, :update!, 4, [file: ~c"lib/keyword.ex", line: 1148]}, {Electric.Replication.PostgresConnectorMng, :update_connector_config, 2, [file: ~c"lib/electric/replication/postgres_manager.ex", line: 119]}, {Electric.Replication.PostgresConnectorMng, :init, 1, [file: ~c"lib/electric/replication/postgres_manager.ex", line: 94]}, {:gen_server, :init_it, 2, [file: ~c"gen_server.erl", line: 2057]}, {:gen_server, :init_it, 6, [file: ~c"gen_server.erl", line: 2012]}]}
```

getting the above when trying to launch the sync service locally using docker + supabase cloud instance

**Comment by brandonkboswell** [comment]
I am also experiencing this when trying to run a local instance of electric with cloud hosted supabase.

**Comment by brandonkboswell** [comment]
@e-lobo FYI I was able to successfully connect when not using a local Docker instance. In my case by using Fly.io with the canary build.

**Comment by alco** [comment]
Hey @e-lobo.

It's really odd you get that error with the `latest` image. I suggest that you try out the latest `canary` again, it has been updated since your original report.

You have to use Supabase's direct connection URL because the pooler does not support opening a replication connection that the sync service needs.

**Comment by KyleAMathews** [comment]
👋 we've been working the last month on a rebuild of the Electric server over at a temporary repo https://github.com/electric-sql/electric-next/

You can read more about why we made the decision at https://next.electric-sql.com/about

We're really excited about all the new possibilities the new server brings and we hope you'll check it out soon and give us your feedback.

We're now moving the temporary repo back here. As part of that migration we're closing all the old issues and PRs. We really appreciate you taking the time to investigate and report the bug!
