### ISSUE TITLE
Failed to initialize postgres state

### ISSUE THREAD

**Issue by Abhishek21k** [electric-sql/electric#1422]
aws ec2 is able to connect successfully to my supabase instance without non pooler connection, so I would assume the ipv6 connection is not an issue, still electric keeps giving this error

also there seems to be some electric schema in my database (not sure if made during this or sometime earlier)
![image3](https://github.com/electric-sql/electric/assets/106271860/b275805e-2a4b-4b4b-aead-46cd1d0cfe73)
![image](https://github.com/electric-sql/electric/assets/106271860/bcfabcc8-e697-4881-9973-415d7169b595)

**Comment by alco** [comment]
Hi @Abhishek21k.

What is the version of the sync service you're using? Have you set the `DATABASE_USE_IPV6` setting to `true`?

**Comment by KyleAMathews** [comment]
👋 we've been working the last month on a rebuild of the Electric server over at a temporary repo https://github.com/electric-sql/electric-next/

You can read more about why we made the decision at https://next.electric-sql.com/about

We're really excited about all the new possibilities the new server brings and we hope you'll check it out soon and give us your feedback.

We're now moving the temporary repo back here. As part of that migration we're closing all the old issues and PRs. We really appreciate you taking the time to investigate and report the bug!
