### ISSUE TITLE
TypeScript Type Errors in generated client with Electric v0.12.1

### ISSUE THREAD

**Issue by Innei** [electric-sql/electric#1432]
Hi, after an evening of research, I finally tried to run electric in a minimal project, and while it now runs without issue, there seems to be a problem with the TypeScript type.
As you can see below, the prisma type generated by the electric client has a very large number of undefined types and an error in the type of liveMany().

```ts
 const { results } = useLiveQuery(db.post.liveMany())
  ^ const results: Omit<$Result.GetResult<Prisma.$PostPayload<$Extensions.DefaultArgs>, S>, “Please either choose `select` or `include`”>[] | undefined
```

![CleanShot 2024-07-30 at 11  27 46@2x](https://github.com/user-attachments/assets/51f72fe8-307b-4858-a469-c0a7848197bd)

```
"electric-sql": "0.12.1",
```

Reproduction Project https://github.com/Innei/electric-demo

```
npm run db:migrate
cd apps/web
npm run client:generate
```

Thank you!

**Comment by KyleAMathews** [comment]
👋 we've been working the last month on a rebuild of the Electric server over at a temporary repo https://github.com/electric-sql/electric-next/

You can read more about why we made the decision at https://next.electric-sql.com/about

We're really excited about all the new possibilities the new server brings and we hope you'll check it out soon and give us your feedback.

We're now moving the temporary repo back here. As part of that migration we're closing all the old issues and PRs. We really appreciate you taking the time to investigate and report the bug!
