### ISSUE TITLE
Add `msgType` differentiator to `Message` interface

### ISSUE THREAD

**Issue by msfstef** [electric-sql/electric#1433]
Currently the `ChangeMessage` and `ControlMessage` coming from upstream can only be differentiated by whether they have an `action` header or `control` header.

This has caused a less than ideal experience in branching off to manage these messages, TS type issues, and I foresee more issues with different clients implemented that will all require to differentiate between the two.

The suggestion is to add a top level property called `msgType`, perhaps integer based (e.g. 0 or 1) to save bandwidth, or `control` and `change` if we don't care that much. If we want this to be part of the protocol at the sync service level then doing an integer flag is probably best.

Suggestion from @samwillis and I, @KyleAMathews also expressed support for easier differentiation.

**Comment by balegas** [comment]
I'm more on the "don't like it side". 
While it gives us a single thing to look for to distinguish between types of messages. We still have to check that a certain property has a certain value and therefore is not a lot different from looking for the existence of a property.

We're changing `action` into `operation`, would it make sense to a `control` operation and drop the `control` header?  cc @KyleAMathews. It is not perfect, but removes any redundancy.

**Comment by KyleAMathews** [comment]
Hmm yeah that's true — moving `control` to a top-level field would make it easier to switch + I agree @balegas that `msgType` is redundant data.

**Comment by balegas** [comment]
@msfstef, when you get here maybe prototype something to see how the typescript types look like?

**Comment by kevin-dp** [comment]
Imo all proposals discussed here for doing type narrowing are dependent on the actual implementation (whether to use a certain field, what is the value of that field, etc.). I think this warrants a lightweight abstraction with simple helper functions that do the narrowing. Implementation details can be hidden behind those functions. See my comment on https://github.com/electric-sql/electric/issues/1453#issuecomment-2291001246

**Comment by msfstef** [comment]
Have we settled on the approach we prefer? And if we're happy to use helper functions should we close this in favour of https://github.com/electric-sql/electric/issues/1453?

**Comment by balegas** [comment]
My preference is that the message schema is not changed for serving the type system and I think the proposal is redundant with other information already in the message.

I like having the helpers. We can change it later.

I suggested using operation: control, which didn’t pick up a lot of interest :D.

**Comment by KyleAMathews** [comment]
Helpers seem fine
