### ISSUE TITLE
Handle WHERE clause string

### ISSUE THREAD

**Issue by balegas** [electric-sql/electric#1439]
Adding a space to a WHERE clause leads to a new shape.

We should be parsing the WHERE clause to avoid duplication of equivalent clauses

```
curl -I -X GET http://localhost:3000/v1/shape/issue\?offset\=-1\&where\=id%3E%3D%27ee77b573-7e60-4f39-8360-97efc63ec2f1%27+and+id%3C%3D%27ee77b573-7e60-4f39-8360-97efc63ec2f2%27

x-electric-shape-id: 57614125-1722603397276
```
```
curl -I -X GET http://localhost:3000/v1/shape/issue\?offset\=-1\&where\=id%3E%3D%27ee77b573-7e60-4f39-8360-97efc63ec2f1%27%20+and+id%3C%3D%27ee77b573-7e60-4f39-8360-97efc63ec2f2%27

x-electric-shape-id: 131749406-1722603458882
```

**Comment by KyleAMathews** [comment]
I'm not sure this matters. Where clauses will be written in code so generally be identical. For optimizations like this, I'd prefer we wait until there's reports in the wild of problems before we work on a fix.

**Comment by KyleAMathews** [comment]
cleaning up issues so going to close this for now. We can re-create if we decide to tackle this in the future.
