### ISSUE TITLE
Prescribe how values of Postgres data types should be encoded in the HTTP API

### ISSUE THREAD

**Issue by alco** [electric-sql/electric#1450]
Following on from https://github.com/electric-sql/electric-next/issues/164, we've arrived at a consensus that column values should be included in JSON responses from our HTTP API as strings. But that's not the end of story, since there's both ambiguity and inefficiencies in saying "just use the stringified value".

Ambiguity comes from the fact that some data types can be formatted differently depending on external factors. Postgres docs on the interval type show an [illustrative example](https://www.postgresql.org/docs/current/datatype-datetime.html#INTERVAL-STYLE-OUTPUT-TABLE) of how the same interval value can be encoded differently depending on the `intervalstyle` setting:

<table class="table" summary="Interval Output Style Examples" border="1">
          <colgroup>
            <col>
            <col>
            <col>
            <col>
          </colgroup>
          <thead>
            <tr>
              <th>Style Specification</th>
              <th>Year-Month Interval</th>
              <th>Day-Time Interval</th>
              <th>Mixed Interval</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><code class="literal">sql_standard</code></td>
              <td>1-2</td>
              <td>3 4:05:06</td>
              <td>-1-2 +3 -4:05:06</td>
            </tr>
            <tr>
              <td><code class="literal">postgres</code></td>
              <td>1 year 2 mons</td>
              <td>3 days 04:05:06</td>
              <td>-1 year -2 mons +3 days -04:05:06</td>
            </tr>
            <tr>
              <td><code class="literal">postgres_verbose</code></td>
              <td>@ 1 year 2 mons</td>
              <td>@ 3 days 4 hours 5 mins 6 secs</td>
              <td>@ 1 year 2 mons -3 days 4 hours 5 mins 6 secs ago</td>
            </tr>
            <tr>
              <td><code class="literal">iso_8601</code></td>
              <td>P1Y2M</td>
              <td>P3DT4H5M6S</td>
              <td>P-1Y-2M3D​T-4H-5M-6S</td>
            </tr>
          </tbody>
        </table>

Taking the venerable `blob` type as another example, both the hex and the escape encodings take up more space than base64, so it would be beneficial if Electric re-encoded values of this type into base64 when preparing a JSON response.

We need to prescribe the format to use for at least for some of the more ambiguous Postgres data types when encoding their values into JSON strings.

TBD a list of candidate types...
-

**Comment by kevin-dp** [comment]
https://github.com/electric-sql/archived-electric-next/pull/230 documents how Postgres values are formatted.
In particular, i'm referring to these changes:
- https://github.com/electric-sql/archived-electric-next/pull/230/files#diff-7e967a724c646d17fe4442f55dd928b9531c08611009b58d56f0f2beaa820807R41
- https://github.com/electric-sql/archived-electric-next/pull/230/files#diff-2bde6cedf9317651a57305b3ed082d5ebcbb4e9923d0c37e076599e6cb05d127R247

I'm closing this issue as it has been addressed by the PR linked above.
If we feel that it requires additional documentation, we can re-open this issue.
