### ISSUE TITLE
Support tables without PKs and changing PKs on a row.

### ISSUE THREAD

**Issue by icehaunter** [electric-sql/electric#1451]
Current protocol assumes an unchanging identity by associating a `key` with each change. Since we're intent on keeping the key, we must split up an `UPDATE` change that affects a PK (entire row in case of PK-less tables, since entire row is the key at that point) into a `DELETE` + `INSERT` pair representing the update each with an individual key. The pair must be still tied in some way by additional metadata for a client to be able to reconstruct the update if it wants to

**Comment by balegas** [comment]
Closed by https://github.com/electric-sql/electric-next/pull/182 https://github.com/electric-sql/electric-next/issues/181
