### ISSUE TITLE
Resource use endpoint?

### ISSUE THREAD

**Issue by thruflo** [electric-sql/electric#1454]
We're doing open telemetry -> honeycomb to get resource use data out of the system. But this requires an external system with persistence, correlation of timing etc.

In many cases, it could be easier to just call an endpoint to get the current resource use stats. That would allow a benchmark to just `GET /_stats` or similar via a simple web request and would be much simpler, operationally.

**Comment by balegas** [comment]
We created the /metrics endpoint
Closed by #1487
