### ISSUE TITLE
Reliability test coverage

### ISSUE THREAD

**Issue by balegas** [electric-sql/electric#1473]
Create an initial reliability test suite.

Look for things that can make Electric break make a test and make it pass.
- Simulate database and server crashes
- Delete the storage; delete the replication slot
- Artificially saturate different parts of the system (e.g. connection pools)
  - Some of this will fit better into load-testing

**Comment by KyleAMathews** [comment]
We've covered some of this — @balegas is there anything left? Want to create issues for each specific thing we still need to test?
