### ISSUE TITLE
Publish a page with FAQs to address common questions re how Electric Next is different from the previous Electric

### ISSUE THREAD

**Issue by alco** [electric-sql/electric#1500]
On Discord, we're seeing people ask similar questions regarding the local-first or offline capabilities of Electric Next, how to sync data to a local database, what clients are supported, etc. We can address those questions that follow the theme "how can I do X in Electric Next when in the previous Electric it was builtin?" where X is any of
- managing migrations (migrations proxy is no longer needed)
- syncing to local DB
- syncing local writes to the server
- electrifying Postgres schema
- scaling the number of users, the size of synced data, etc.

We can also preempt a bunch of questions about performance and capabilities that fall out naturally from the docs we've put out in the open so far:
- what are some concrete benchmarks that back our scalability claims?
- how does authorization work?
- how does PGlite fit into the picture of syncing with Electric Next?

The aim of having a decidated FAQ page is to provide quick answers to very specific questions as opposed to asking everyone to read through a wall of text on our About page or a hypothetical Architecture page.

**Comment by KyleAMathews** [comment]
It seems like most of these specific comparison questions are being handled in Discord and/or are covered by more specific doc issues.
