### ISSUE TITLE
Write a test that verifies the idempotency of processing the same transaction more than once

### ISSUE THREAD

**Issue by alco** [electric-sql/electric#1505]
The situation when Electric receives the same transaction more than once via the replication stream can arise in the following scenario. When the database cluster shuts down, all of Electric's connections to the database will close and Electric will go into the reconnection-with-backoff loop. Once Postgres comes back up, Electric will be able to resume its logical replication stream from the same point at which it stopped streaming previously thanks to the persistent replication slot it had created.

If Electric has processed a transaction (by persisting it to the shape log) but hasn't acknowledged its WAL offset to Postgres because the connection was closed, the next time Postgres starts, Electric will read the already seen transaction from the logical stream once again.

**Comment by balegas** [comment]
I had a brief chat with @icehaunter about this. It looks like our storage will re-write over the key for the offse.

1. Let's make the test to validate that
2. Should we skip writing if the shape is ahead of the log from PG?
