### ISSUE TITLE
linear-lite example ran into "ERROR! Config provider Config.Reader failed with" for backend-1 container

### ISSUE THREAD

**Issue by archywillhe** [electric-sql/electric#1510]
I git cloned and followed the readme in the linear-lite example, and everything works well except the docker container crashed

**Comment by archywillhe** [comment]
the docker containter at port 3000 crashed with the following logs:

```
ERROR! Config provider Config.Reader failed with:
 ** (RuntimeError) Required environment variable LOGICAL_PUBLISHER_HOST is not set
 /app/releases/0.8.1/runtime.exs:34: (file)
```

everything else is fine

**Comment by alco** [comment]
Hey @archywillhe. The problem is that your Docker containers runs a Docker image of old Electric. If you're using `electricsql/electric` or `electricsql/electric:latest` for the Docker image, try pulling a fresh version from Docker Hub by running `docker pull electricsql/electric`.

**Comment by archywillhe** [comment]
hi @alco thanks for the quick tips! Yeah it's working perfectly now!
