### ISSUE TITLE
Failing to serve shape log

### ISSUE THREAD

**Issue by kevin-dp** [electric-sql/electric#1526]
As per this report on [Discord](https://discord.com/channels/933657521581858818/1273350209157595171/1273372860551008488), it seems that there is a bug in the sync service which causes it to pass a wrong `last_offset` to the `get_log_stream` function and thus fails to retrieve the shape log. This is the relevant part of the backend log:

```
electric-1  |
electric-1  | 19:49:21.801 [error] ** (Plug.Conn.WrapperError) ** (FunctionClauseError) no function clause matching in Electric.ShapeCache.Storage.get_log_stream/4
electric-1  |     (electric 0.2.7) lib/electric/shape_cache/storage.ex:128: Electric.ShapeCache.Storage.get_log_stream("69258598-1723664840890", LogOffset.new(78166000, 0), LogOffset.new(0, 0), {Electric.ShapeCache.CubDbStorage, %{db: :shape_db, file_path: "./shapes"}})
electric-1  |     (electric 0.2.7) lib/electric/plug/serve_shape_plug.ex:301: Electric.Plug.ServeShapePlug.serve_log_or_snapshot/2
electric-1  |     (electric 0.2.7) lib/electric/plug/serve_shape_plug.ex:1: Electric.Plug.ServeShapePlug.plug_builder_call/2
electric-1  |     (electric 0.2.7) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in Electric.Plug.Router.dispatch/2
electric-1  |     (telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
electric-1  |     (electric 0.2.7) deps/plug/lib/plug/router.ex:242: Electric.Plug.Router.dispatch/2
electric-1  |     (electric 0.2.7) lib/electric/plug/router.ex:1: Electric.Plug.Router.plug_builder_call/2
electric-1  |     (bandit 1.5.5) lib/bandit/pipeline.ex:124: Bandit.Pipeline.call_plug!/2
electric-1  |     (bandit 1.5.5) lib/bandit/pipeline.ex:36: Bandit.Pipeline.run/4
electric-1  |     (bandit 1.5.5) lib/bandit/http1/handler.ex:12: Bandit.HTTP1.Handler.handle_data/3
electric-1  |     (bandit 1.5.5) lib/bandit/delegating_handler.ex:18: Bandit.DelegatingHandler.handle_data/3
electric-1  |     (bandit 1.5.5) /app/deps/thousand_island/lib/thousand_island/handler.ex:411: Bandit.DelegatingHandler.handle_continue/2
electric-1  |     (stdlib 6.0.1) gen_server.erl:2163: :gen_server.try_handle_continue/3
electric-1  |     (stdlib 6.0.1) gen_server.erl:2072: :gen_server.loop/7
electric-1  |     (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
electric-1  |
electric-1  |
```

This is about this Elixir function from `Storage` which is not matching the call:
```ex
def get_log_stream(shape_id, offset, max_offset \\ LogOffset.last(), {mod, opts})
  when max_offset == :infinity or not is_log_offset_lt(max_offset, offset),
  do: mod.get_log_stream(shape_id, offset, max_offset, opts)
```

So, basically, `get_log_stream` fetches a portion from the log from offset till max_offset. Therefore, the guard checks that the `max_offset` is bigger or equal to the start offset (i.e. not lesser than is the same as bigger or equal than). However, somehow, the `max_offset` in the call is the very first log offset (0, 0). And thus this function does not match, hence, the error.

This `Storage.get_log_stream/4` function is called by `Electric.Shapes.get_log_stream/3` which fetches the `offset` and `max_offset` from the `opts` it gets:
```ex
def get_log_stream(config, shape_id, opts) do
  offset = Access.get(opts, :since, LogOffset.before_all())
  max_offset = Access.get(opts, :up_to, LogOffset.last())
  storage = Access.fetch!(config, :storage)
  Storage.get_log_stream(shape_id, offset, max_offset, storage)
end
```

This `Electric.Shapes.get_log_stream/3` function is called in 2 places in the shape plug in `Electric.Plug.ServeShapePlug.serve_log_or_snapshot/2`. Both calls essentially fetch the `offset` and `max_offset` from the connection's `assigns.offset` and `assigns.last_offset`.

The `assigns.last_offset` is set initially when loading the shape info (when the request comes in) and updated in `hold_until_change` (i.e. only in live mode) when a new change comes in. I'm suspecting that there is a condition that triggers a shape rotation (that condition can only be a truncate?) which causes the latest offset to become (0, 0) and `hold_until_change` then updates the `last_offset` to (0, 0). This is a wild guess though, would that be possible? We should try to reproduce.

**Comment by KyleAMathews** [comment]
Do we have a reproduction for this @alco

**Comment by alco** [comment]
Hey @KyleAMathews. I've only just started looking into it. I noticed that the function guard is incorrect when I first read the description, fix is pending in https://github.com/electric-sql/electric/pull/1557. Writing a regression test is up next on my list.

**Comment by alco** [comment]
I haven't been able to reproduce this. When a table is truncated, the client gets the 409 response regardless of whether it sends a regular or a live request for the shape ID.

Closing this as a non-issue.
