### ISSUE TITLE
JSONB fields that are null are sent as empty string.

### ISSUE THREAD

**Issue by MAST1999** [electric-sql/electric#1536]
To reproduce it, create a table with a JSONB field and insert some data but leave the JSONB field to be null.
Request the shape for table, and you will see the JSONB field being sent as an empty string, but it should be null.

This causes the sync to pglite to fail because, parsing an empty string throws.

Here's a [link](https://discord.com/channels/933657521581858818/933657523049885698/1274436467309154306) discussion related to this issue in Discord.

**Comment by kevin-dp** [comment]
Hi @MAST1999, thank you for reporting this bug. This bug should be fixed as soon as this [PR](https://github.com/electric-sql/electric/pull/1532/files#diff-6568fbb0e1993af7bdaf8f3406097e3e5371842a22c81e40324648ce538c76e7R164) is merged.
