### ISSUE TITLE
Use Caddy in dev docker compose

### ISSUE THREAD

**Issue by balegas** [electric-sql/electric#1546]
We documented using Caddy to setup a reverse proxy for local dev (#1545), but our own dev compose uses NGINX. We should change our dev image to use Caddy. Let's also turn on GZip encode for improved performance.

**Comment by balegas** [comment]
Cancelling the issue because, contrarily to my assumptions, Caddy doesn't seem to offer out-of-the-box http caching support.

**Comment by KyleAMathews** [comment]
Huh that is surprising. I guess they're really focused on the https/proxy aspect 🤷 there's this https://github.com/caddyserver/cache-handler but that'd be more config when nginx works great OOTB.

**Comment by balegas** [comment]
Yeah. We looked at it but didn’t seem the common pattern.
