### ISSUE TITLE
Return larger shape logs in chunks

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#1581]
It's not a good idea to return huge shape logs in one request as:
- many HTTP proxies won't cache large shapes (e.g. 20mb+)
- clients can't process the shape log until they finish downloading it — e.g. if a client is inserting data into pglite, it'd be faster if they could parallelize downloading/parsing data with inserting rows into pglite. The same is true of any integration.

Ideal chunk size is around ~10mb.

The API was designed for this as clients continue requesting data until they the server reports they're at the end of the log so there'd be no breaking changes required for this.

**Comment by msfstef** [comment]
@kevin-dp and I are workshopping this - will keep the thread updated
