### ISSUE TITLE
Crashing Shape consumer should resume at a consistent point

### ISSUE THREAD

**Issue by magnetised** [electric-sql/electric#1585]
With the old single-process model, if a write to storage failed with some error it would crash the log collector process, which would in turn crash the replication producer process. On restarting the replication stream would resume from the last unacked point and, due to idempotent storage apis, all the shapes would resume at a consistent point.

Under the new multi-process model,  a consumer crashing due to some underlying storage issue will be restarted but the replication stream would have been progressing without it and the crashing shape would resume at some random point in the replication stream.

A crashing consumer should resume at a consistent point. A potential solution is to replicate the previous behaviour, a crashing consumer crashes everything, including the replication producer, and when everything restarts it will do so as before, with postgres resuming the replication stream at the last un-acked point and all clients receiving all transactions.

**Comment by KyleAMathews** [comment]
Another option, given I assume crashing due to storage should be very rare, is to just delete the shape and let it restart. Crash only programming!
