### ISSUE TITLE
Please add a light mode to your websites, increases readability

### ISSUE THREAD

**Issue by voltuer** [electric-sql/electric#1609]
Hi, I'm from the team light, I find it hard to read websites with dark mode, and it's been [scientifically proven](https://www.youtube.com/watch?v=Ieq5sNEoc1E&t=183s) that light mode increases readability, so please give us a light mode version of both your website and your documentation.

**Comment by thruflo** [comment]
Hi, thanks for the suggestion. However there’s a non-negligible overhead maintaining two modes. Particularly in mastering diagrams. So we’re going to stick dark mode only for now.
