### ISSUE TITLE
Database connection failed: no pg_hba.conf entry for host

### ISSUE THREAD

**Issue by matt-aitken** [electric-sql/electric#1620]
## Summary

I can't connect Electric to my AWS Aurora Postgres 14.7 database using the `DATABASE_URL`. This is reproducible using Docker Desktop locally and in AWS on the deployed AWS Fargate instance.

This is the error inside the Electric Docker container:

```
2024-09-03 18:08:51 
2024-09-03 18:08:51 17:08:51.831 [info] Loading 140 CA(s) from :otp store
2024-09-03 18:08:51 
2024-09-03 18:08:51 17:08:51.844 [info] Running Electric.Plug.Router with Bandit 1.5.5 at 0.0.0.0:3000 (http)
2024-09-03 18:08:52 
2024-09-03 18:08:52 17:08:52.330 [warning] Database connection failed: no pg_hba.conf entry for host "XX.XXX.XX.XX", user "electric", database "pgtrigger", SSL encryption (PG code: 28000, PG routine: ClientAuthentication)
2024-09-03 18:08:52 
2024-09-03 18:08:52 17:08:52.331 [warning] Reconnecting in 2000ms
```

### sslmode ⛔
With `?sslmode=require` and without doesn't work.

### Connecting from the same Docker container using psql ✅
In the same Docker container I used exec to install `psql` and then successfully executed this command:

```
# psql "postgresql://electric:XXXXXXX@trigger-app-test-database.cluster-xxxxxxxxxxxxxx.us-east-1.rds.amazonaws.com/pgtrigger?sslmode=require"
psql (15.8 (Debian 15.8-0+deb12u1), server 14.7)
SSL connection (protocol: TLSv1.2, cipher: AES128-SHA256, compression: off)
Type "help" for help.

pgtrigger=> SELECT version();
                                                   version                                                   
-------------------------------------------------------------------------------------------------------------
 PostgreSQL 14.7 on aarch64-unknown-linux-gnu, compiled by aarch64-unknown-linux-gnu-gcc (GCC) 9.5.0, 64-bit
(1 row)
```

### Minimal Elixir app dockerized works ✅

A very simple Elixir app that uses Postgrex and is Dockerized works. This is the main bit of code:

```ex
defmodule DBTest do
  def connect do
    {:ok, pid} = Postgrex.start_link(
      hostname: "trigger-app-test-database.cluster-ro-xxxxxxxxx.us-east-1.rds.amazonaws.com",
      username: "electric",
      password: "xxxxxxxxxxxx",
      database: "pgtrigger",
      ssl: true,
      ssl_opts: [verify: :verify_none]
    )
    Postgrex.query!(pid, "SELECT 1", [])
  end
end
```

I turned this into a Docker image with this Dockerfile:

```
# Use an official Elixir runtime as a parent image
FROM elixir:latest

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install hex package manager
RUN mix local.hex --force

# Install rebar (Erlang build tool)
RUN mix local.rebar --force

# Install dependencies
RUN mix deps.get

# Compile the project
RUN mix compile

# Set the default command to run your script
CMD ["mix", "run", "test_connection.exs"]
```

And it correctly logs out this:

```
docker run -it --rm my-elixir-app

19:30:00.390 [warning] setting ssl: true on your database connection offers only limited protection, as the server's certificate is not verified. Set "ssl: [cacertfile: path/to/file]" instead
Connection result: %Postgrex.Result{
  command: :select,
  columns: ["?column?"],
  rows: [[1]],
  num_rows: 1,
  connection_id: 22826,
  messages: []
}
```

Note that it does log a warning about the certificate though.

## Certificates

I tried listing the certificates from inside the Electric docker image:

```
ls -l /etc/ssl/certs
```

This does not include the default AWS RDS certificate (which we use): rds-ca-rsa2048-g1

**Comment by kevin-dp** [comment]
Hi @matt-aitken, did you configure your `pg_hba.conf` file as explained in the [Postgres documentation](https://www.postgresql.org/docs/current/auth-pg-hba-conf.html) ?

I believe that the default `pg_hba.conf` file only allows local connections. From the error message, it looks like you're trying to connect remotely and forgot to add an entry for that host in the `pg_hba.conf` file.

When you say that you can connect to your PG DB on AWS via a local docker container, is that container running on host "XX.XXX.XX.XX" as reported by the error message? Maybe you're running the container locally on your machine and properly configured `pg_hba.conf` to allow connections from your machine, but forgot to allow connections from "XX.XXX.XX.XX" which is why the connection fails when you try to run it there?

**Comment by matt-aitken** [comment]
I don’t think that’s the issue. 

As I mentioned, I can connect to that database from my local machine – we do it everyday. I also created a simple Elixir app running in Docker on my machine that does successfully connect.

AWS Aurora doesn’t have a pg_hba.conf file but it has the settings and they’re configured to allow access publicly in this case (though not for our prod database).

**Comment by icehaunter** [comment]
Issue here is explicitly with `replication=database` option when connecting -- reproducible with a plain `psql` request. The DB wasn't configured for logical replication, as per https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Replication.Logical.Configure.html
