### ISSUE TITLE
Error with cors when connecting with `electric-sql/react` to `electricsql/electric`

### ISSUE THREAD

**Issue by SandroMaglione** [electric-sql/electric#1623]
I was following the quickstart at [next.electric-sql.com](https://next.electric-sql.com/guides/quickstart).

Great work on that, all steps working without problems. The only roadblock I am getting is at the very end when connecting with `useShape` to the localhost api. I am getting a cors error:

```sh
Access to fetch at 'http://localhost:3000/v1/shape/foo?offset=-1' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

<img width="647" alt="スクリーンショット 2024-09-04 11 25 00" src="https://github.com/user-attachments/assets/540ade43-7441-4478-9c60-c6df9ca6a8db">

Is is possible to update the cors configuration for the `electricsql/electric` localhost server? Or does this require a change in the docker image itself?

If it helps, the repo I am using is [open source here](https://github.com/SandroMaglione/pglite-client-server).

**Comment by KyleAMathews** [comment]
hey I just ran through the quickstart again and couldn't reproduce this. Two possible things to check:
1. look at the headers for the shape request — is the response actually coming from Electric? Perhaps there's something else sitting on port 3000.
2. do you have the latest docker image? Try running `docker pull electricsql/electric` and then stopping and deleting your docker containers and starting them over (creating the table, inserting data, etc).

**Comment by SandroMaglione** [comment]
> Perhaps there's something else sitting on port 3000.

That was it 🤦
