### ISSUE TITLE
Chunking algorithm is creating very small chunks

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#1667]
I have a shape that probably now has several 1000 operations in it. For some reason the chunking algorithm is returning an initial chunk with 87 messages than over a hundred now different chunks, each with 37 messages in it.

The total data transferred is still only 150 kb so I'd expect that there'd still be only one chunk not hundreds. The number of chunks is creating a noticeable delay now in starting the app.

<img width="1758" alt="Screenshot 2024-09-10 at 1 16 58 PM" src="https://github.com/user-attachments/assets/1149e38b-c43a-481b-86ea-364f3d6a3bd1">

**Comment by KyleAMathews** [comment]
Another in-the-wild report of this https://discord.com/channels/933657521581858818/1280199098833698889/1284213285666689146

**Comment by KyleAMathews** [comment]
Another one https://discord.com/channels/933657521581858818/1284719450544803954/1284723039686098998

**Comment by msfstef** [comment]
Closing as https://github.com/electric-sql/electric/pull/1704 should address this - it was chunking at 10kB rather than 10MB
