### ISSUE TITLE
TS Client crashes when a column named value is null

### ISSUE THREAD

**Issue by dustin-H** [electric-sql/electric#1673]
I created this issue to explain https://github.com/electric-sql/electric/pull/1668 as requested by @kevin-dp [here](https://github.com/electric-sql/electric/pull/1668#pullrequestreview-2297517100).

When a shape includes a column named `value`, that is nullable and currently null or set to null, the typescript client is crashing:

<img width="637" alt="Screenshot 2024-09-11 at 07 20 16" src="https://github.com/user-attachments/assets/0667fcc4-aa32-4a2f-9d29-3866fc1e53bc">

## Steps to reproduce:

1) Setup electric as described in [Quickstart Guide](https://electric-sql.com/docs/quickstart) including the table `foo`.
2) Insert a row with `value=null`: `INSERT INTO "public"."foo"("name") VALUES('Hans');` (value is null)
3) Now the above error occurs in the browser.

I already created this PR to fix it: #1668

**Comment by kevin-dp** [comment]
Hi @dustin-H,

Thanks for the bug report!
I was able to reproduce it and your fix with the updated test case looks good!
Thank you for contributing this fix 🥇
