### ISSUE TITLE
Deleting the only shape causes the ReplicationClient to crash

### ISSUE THREAD

**Issue by robacourt** [electric-sql/electric#1688]
Steps to reproduce:

```sql
CREATE TABLE items ( id UUID PRIMARY KEY, value TEXT NOT NULL)
```

```bash
http GET :3000/v1/shape/items offset==-1

http DELETE :3000/v1/shape/items shape_id==[SHAPE_ID]
```

```sql
INSERT INTO items VALUES (gen_random_uuid(), 'test value 1')
```

This produces the following error message on the server repeatedly every 5 seconds:

```
16:06:39.924 [error] :gen_statem #PID<0.687.0> terminating
** (stop) exited in: GenServer.call(Electric.Replication.ShapeLogCollector, {:new_txn, %Electric.Replication.Changes.Transaction{xid: 747, commit_timestamp: ~U[2024-09-13 15:06:29.858947Z], lsn: #Lsn<0/198D920>, last_log_offset: LogOffset.new(26794272, 0), changes: [%Electric.Replication.Changes.NewRecord{relation: {"public", "items"}, record: %{"id" => "04712b05-946e-4908-9433-3abbadb01e59", "value" => "test value 1"}, log_offset: LogOffset.new(26794272, 0), key: nil}], affected_relations: MapSet.new([{"public", "items"}])}}, 5000)
    ** (EXIT) time out
    (elixir 1.17.2) lib/gen_server.ex:1128: GenServer.call/3
    (electric 0.4.3) lib/electric/postgres/replication_client.ex:227: Electric.Postgres.ReplicationClient.handle_data/2
    (postgrex 0.19.0) lib/postgrex/replication_connection.ex:551: Postgrex.ReplicationConnection.handle/5
    (postgrex 0.19.0) lib/postgrex/replication_connection.ex:537: Postgrex.ReplicationConnection.handle_data/2
    (stdlib 6.0.1) gen_statem.erl:3115: :gen_statem.loop_state_callback/11
    (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
```

This also seems to stop the processing of the WAL potentially bloating the buffer on Postgres. Requesting another shape fixes the issue.

Deleting a shape when there are other shapes remaining does not elicit this issue.

**Comment by robacourt** [comment]
I found this as part of trying to fix this sporadic test "test /v1/shapes DELETE forces the shape ID to be different on reconnect and new snapshot to be created (Electric.Plug.RouterTest)" seen failing [here](https://github.com/electric-sql/electric/actions/runs/10794265494/job/29938152963). Fixing this issue should also fix the sporadic test.

**Comment by robacourt** [comment]
`ShapeLogCollector.handle_transaction/3` replies if it has no subscribers or waits for the subscribers to create demand if there are subscribers. If there are subscribers but their selector doesn't match the event then no demand will be generated and the call to `ShapeLogCollector.store_transaction/2` gets stuck and after 5 seconds times out.

On delete of the last shape, the only subscriber left is the ShapeCache which does not have transactions in it's selector, so no demand will be generated and the call to `ShapeLogCollector.store_transaction/2` will time out.

The only way I can think to fix this would be to check not only if there are any subscribers but if there are subscribers with selectors that match the event but the ShapeLogCollector does not know about the selectors. Or allow the ShapeLogCollector to know that it has the ShapeCache subscribed and skip it when it's checking for subscribers, but it doesn't feel very neat to add this dependency. @magnetised any ideas?

**Comment by robacourt** [comment]
When this is fixed, please remove the extra shape creation in this test: https://github.com/electric-sql/electric/blob/4c21b5623ddd9d077f37ce83fafb1445dee50c9f/packages/sync-service/test/electric/plug/router_test.exs#L121

**Comment by magnetised** [comment]
@robacourt lemme think about it. there might be something we can do in the dispatcher that handles this case, the dispatcher knows about both the subscribers and the selectors.

I'll take this over if that's ok?
