### ISSUE TITLE
Move WHERE clause evaluation to single process

### ISSUE THREAD

**Issue by balegas** [electric-sql/electric#1744]
We're doing shape where clause filtering inside the process that owns the shape log. While processes are cheap in Elixir, we're copying a lot of memory around for each shape and launching async work that ends up being discarded because a single write operation only touches to a few shapes.

We think this is adding a significant compute overhead to the server and want to test an alternative solution where shape where clauses are evaluated in a single process and write operations are sent only to the shape owners that will actually write to the shape log.

- [ ] Try [this](https://github.com/electric-sql/electric/issues/1744#issuecomment-2368163910) suggestion or open a follow-up issue

**Comment by marc-shapiro** [comment]
May I suggest going one step further, and maintaining a single shape log for all subscribers.  You get performance advantages: sequential writes and less bursty I/O.

**Comment by balegas** [comment]
That's a radical :D. I think shape interleaving is worth exploring since the CDN will cache what you want after a first call. Would also be useful for parametrised shape that are not updated frequently.

It is worth investigating, but let's do the pragmatic steps first.

**Comment by KyleAMathews** [comment]
Hmm yeah that is a cool idea. Scanning a file and filtering out rows by shape id would be really fast as long as there wasn't too many shapes interwoven.
