### ISSUE TITLE
Shape API tweaks

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#1771]
A few things have come up:

## Proposal: move table from its current place as the last path segment to just another (required) query argument.

The root table for a shape is currently in the API path e.g. `v1/shape/${table_name}`. This is a required parameter and my original logic to do it this way was basically that it's easy to write when testing out simple shape per table shapes. E.g. `curl http://localhost:3000/v1/shape/foo`.

But it does get a bit weird as people might need to specify the schema the table is part of. Also there's an odd chance that in the future, we'll support alternative backends that don't have "tables". Also we might want to have some sort of multi-table syntax. Regardless, moving the table out of the path gives us more flexibility.

So that foo shape curl above would look like:

`curl http://localhost:3000/v1/shape?table=foo`

## Proposal: change `shape_id` to `shape_handle`

The problem with `id` is it strongly suggests that it's a permanent identifier for the particular shape. Whereas it's just pointing to a particular ephemeral instantiation of the shape. A particular shape instantiation be removed at any moment so we need a term that conveys the idea of a unique identifier that you can use to access or manipulate a specific instance of the shape log.

`handle` is often used for this sort of thing.

`token` is another term I considered but it has too much whiff of session-y or authorization related usage.

**Comment by balegas** [comment]
> curl http://localhost:3000/v1/shape?table=foo
I think this will age a lot better as we add more complex shape definitions
