### ISSUE TITLE
Electric no longer performs automatic fallback to disabling SSL for database connections

### ISSUE THREAD

**Issue by alco** [electric-sql/electric#1792]
Prior to #1762, Electric tried to connect to the database using SSL first, then fall back to using an unencrypted connection unless the DATABASE_URL config had the `sslmode` query parameter in it.

#1762 made changes to the DB connection setup and, as an accidental side effect, Electric no longer performs the automatic fallback. I believe this wouldn't have happened if the fallback logic hadn't been moved from `ConnectionManager` to `ReplicationClient` in #1594.

To fix this regression, we need to move the fallback logic back to `ConnectionManager` and add an integration test to preclude future regressions.

**Comment by balegas** [comment]
- [ ] let's not forget to revert in https://github.com/electric-sql/electric/pull/1781#issuecomment-2391568141
