### ISSUE TITLE
Sync service's supervision tree design leads to invalid startup sequences

### ISSUE THREAD

**Issue by alco** [electric-sql/electric#1817]
We have the root supervision tree in the `Application` module but it's really bare bones. The process trees reponsible for maintaining individual shapes are started at a later point in time, on demand. 

The current design and split of different sub-supervisors between files makes the initialization sequence too opaque. As a consequence, we have a failure state caused by a `Snapshotter` process trying to access the database before the DB connection pool has been started. See, for example,
* https://github.com/electric-sql/electric/actions/runs/11250979969/job/31281239838
* https://github.com/electric-sql/electric/actions/runs/11251255328/job/31285173176

To fix this, we need to reorganize the code such that the start sequence for the core processes, such as the replication client and the DB connection pool, is clearly visible in the code and clearly happens before shape-specific supervision trees are started.

**Comment by msfstef** [comment]
Closing this as @alco 's PRs addressing this have now been merged
