### ISSUE TITLE
Make better error when Electric can't connect to the database

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#1825]
Right now if you type the wrong database name in your postgres string, you'll get the following error:

`** (Postgrex.Error) ERROR 55000 (object_not_in_prerequisite_state) replication slot "electric_slot_default" was not created in this database`

Instead we should just say something more helpful like that we could connect but the database name isn't correct. I'm assuming we are connecting but then the replication slot creation fails — so we could put in a check that the database exists first.

**Comment by robacourt** [comment]
I just tried in main (d43c375) and got:

```
09:29:26.784 [warning] Database connection in lock_connection mode failed: database "wibble" does not exist (PG code: 3D000, PG routine: InitPostgres)
```

Which is already pretty helpful.

**Comment by balegas** [comment]
I think that's fine. People might not know what `lock_connection` is but message is fine.
