### ISSUE TITLE
Add error monitoring framework to Electric

### ISSUE THREAD

**Issue by msfstef** [electric-sql/electric#1849]
It would be good to include an error monitoring tool, like [Sentry](https://sentry.io/welcome/) or [AppSignal](https://www.appsignal.com/), even if it is just for development environments.

**Comment by KyleAMathews** [comment]
Like a doc page I assume?

**Comment by msfstef** [comment]
I meant more to integrate an error monitoring library in the sync service itself and setting up a project for it to start tracking errors directly, at least from our own testing, examples, and deployments

**Comment by KyleAMathews** [comment]
Done: https://github.com/electric-sql/electric/pull/2099
