### ISSUE TITLE
Add way to cleanup replication slots

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#1854]
When shutting down Electric, sometimes we'll want to cleanup replication slots in Postgres. E.g. a PR environment where Electric is spun up for some tests and then shut down again.

Perhaps this is an environment variable? `CLEANUP_REPLICATION_SLOTS_ON_SHUTDOWN`

**Comment by alco** [comment]
If this is a separate operational mode from the regular one, it's best to use an env variable that will instruct Electric to create a temporary slot (as opposed to the regular persistent one). Then Postgres will automatically remove the slot when the replication connection closes.
