### ISSUE TITLE
Will changing from `PORT` to `ELECTRIC_PORT` break deployment compatibility?

### ISSUE THREAD

**Issue by thruflo** [electric-sql/electric#1933]
Quite a few deployment platforms automatically set a PORT env var for services to pick up on and bind to. By renaming PORT to ELECTRIC_PORT, might we sometimes miss out on binding to the right port?

For example, Render say you “must” bind to PORT (although they also say that in most cases they will detect if you bind to a different one) in https://docs.render.com/web-services#port-binding

So, I’m not quite sure what the real world impact of this is but perhaps it’s safer to fallback on PORT if ELECTRIC_PORT isn’t set?

**Comment by KyleAMathews** [comment]
Hmm in Render's case you'd just set `ELECTRIC_PORT` to 10000 (the default port).

Perhaps we just wait for someone to report that they can't figure out how to set the port before doing the fallback? I've never heard of a system that _requires_ the use of `PORT`. That seems pretty rigid.

**Comment by thruflo** [comment]
A silly idea but perhaps we could support setting `ELECTRIC_PORT=PORT` just for this particular case (Ie set to the literal string value “PORT” to say “go read this from the PORT env var”)?!

**Comment by KyleAMathews** [comment]
Again I don't think this is a big deal — I didn't know any service even had a default PORT you had to bind to like Render. Most I've seen you just specify the external and internal port directly so most people would just use the default Electric port.

**Comment by thruflo** [comment]
My experience is that more PaaS-y providers do set PORT and expect you to use it. Eg: https://devcenter.heroku.com/articles/preparing-a-codebase-for-heroku-deployment#4-listen-on-the-correct-port

It does seem that most provide a mechanism to set / override it. And the type of provider that gives you a persistent disk allows you to specify your ports.

It is just a slightly unnecessary regression, in that PORT is a standard, very much like DATABASE_URL is.

**Comment by KyleAMathews** [comment]
The [point of the change](https://github.com/electric-sql/electric/issues/1927) was to avoid the chance of namespace collision when running multiple bits of software in the same environment — e.g. imagine if someone ran Electric, Postgres, and a node app together on their computer. They'd want to set `PORT` for the node app, `PGPORT` for Postgres, and `ELECTRIC_PORT` for Electric. If we used `PORT` then the node app and Electric would both try to use the same port.

So we're trying to _avoid_ common names because odds are something else will already be using it in this collision edge case. `DATABASE_URL` is the one exception because it's quite common for a number of services to all want to connect to the same database so they do share that.

**Comment by thruflo** [comment]
Yup, I understand the rationale. Even if likelihood of a clash is small (docker doesn’t just read env vars from the host) it’s better to namespace to avoid them.

There is just a minor impact on compatibility with deployment services that set / expect you to read PORT. We could trivially mitigate this with an `if ELECTRIC_PORT elif PORT else 3000`.

**Comment by KyleAMathews** [comment]
Yeah but that'd fail in the case PORT is set for another app and the user expects Electric to be running on its default port.

**Comment by thruflo** [comment]
Hence `ELECTRIC_PORT=PORT`.

Fwiw I've done an example implementation in https://github.com/electric-sql/electric/pull/1940

I think it's harmless and add compatibility. But please do merge or close as you prefer. I don't mind either way and I don't want to add complexity for minor gain if the benefit isn't convincing.

**Comment by KyleAMathews** [comment]
Oh like a magic env variable — I see... yeah... I like convenience and magic when there's a clear and significant need but every feature and every bit of code has a significant ongoing cost so let's wait until we here from people that it's actually quite cumbersome to get the ports right.
