### ISSUE TITLE
Simplifying React Usage

### ISSUE THREAD

**Issue by harrysolovay** [electric-sql/electric#1964]
It would be great if instead of a `useShape` hook, there was a factory that would output a hook with common types/options already applied.

**Current:**

```ts
const { data } = useShape<T>({
  url: process.env.ELECTRIC_PROXY_URL!,
  table: "table_name",
  where: `table_id = '${table_id}'`,
})
```

**Proposal:**

```ts
const useShape = UseShape<L>({
  url: process.env.ELECTRIC_PROXY_URL!,
})

const { data } = useShape({
  table: "table_name",
  where: `table_id = '${table_id}'`
})
```

> `L` denotes a would-be lookup type, where row object types are keyed by table name.

This typing could also prevent specifying non-existent `table`s.

I believe this approach would work really well with tools like `kysely-codegen` which output a single `DB` type:

```ts
const useShape = UseShape<{
  [K in keyof DB]: Selectable<DB[K]>
}>({
  // ....
})
```

**Comment by KyleAMathews** [comment]
We've thought about this but have found it's fairly easy to create our own little factory functions which generate the options. There's a lot of ways people could construct the options so we're hesitant to add an opinionated way directly in the library.

**Comment by KyleAMathews** [comment]
Would using your own helper function work for you?

**Comment by harrysolovay** [comment]
That's reasonable. I agree! Will close out this issue.

If it happens to be useful for others, here's an example of such a util / `useShape` wrapper:

```ts
import { ShapeStreamOptions } from "@electric-sql/client"
import { useShape as useShape_ } from "@electric-sql/react"
import { Selectable } from "kysely"
import { DB } from "schema"

export function useShape<K extends keyof DB>(
  table: K,
  options: Omit<ShapeStreamOptions<Selectable<DB[K]>>, "url" | "table" | "parser"> = {},
) {
  return useShape_<Selectable<DB[K]>>({
    url: `${process.env.EXPO_PUBLIC_CROSSHATCH_SERVER}/v1/shape`,
    table: `public.${table}`,
    ...options,
  })
}
```

**Comment by KyleAMathews** [comment]
Very nice! Love using Kysely to get the types automatically.

**Comment by KyleAMathews** [comment]
Very cool! We're looking at using Kysely for Electric Cloud actually so will probably be following your footsteps pretty soon :-D

> Loving Electric btw!

Great to hear! What are you working on (if you can share)?

**Comment by harrysolovay** [comment]
I can't at the moment. But hopefully very soon.
