### ISSUE TITLE
The client isn't automatically handling shape definition / handle mismatch

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#1974]
The client should never get stuck if it's sending a valid shape definition.

It seems we're returning a 400 in some cases when the shape def & handle don't match but the shape def *is* valid — the 400 stops the client.

"hiko" on discord (don't know their github handle) says if you refresh the browser a few times then the error goes away which strongly suggests that the browser had cached a shape response to a handle that went away and then the server is for some reason not returning a 409 to get the client to refetch.

**Comment by msfstef** [comment]
Seems like it could be because of inconsistent behaviour between `Shapes.get_shape` and `Shapes.has_shape?`, where the latter "waits" for a shape if it isn't immediately available, so the first check might fail while the second doesn't because of a race, ending up in this situation.

**Comment by r3lays** [comment]
Can provide more context if needed here! - hiko

**Comment by msfstef** [comment]
@r3lays hey! thank you for joining - my suspicion would be that this occurs around the time a migration happens, as this would require a shape to be deleted (unless you are deleting any shapes explcitly) - is any of these the case?

**Comment by r3lays** [comment]
Can you clarify what you mean by migration?

I did restart and clear the server before bringing things live into preview.

**Comment by msfstef** [comment]
> Can you clarify what you mean by migration?

Potentially altering the table that you're syncing from postgres (adding/removing a column or anything like that)

> I did restart and clear the server before bringing things live into preview.

Were you running it in non-production environments before? Or were you already in production and restarted? Also, when you say "clear the server" do you mean clearing the storage and booting up a new "fresh" server?

**Comment by r3lays** [comment]
No migration then - the structure has been the same throughout the entire integration.

We have two environments. I had the preview server live but it was not in use yet. 
I was using the dev environment thats setup on a server as well and it was giving me the same issues occasionally.

Before getting my changes live into preview, I cleared the state and brought the containers down.
 
```docker compose down --volumes``` and then restarted them.

**Comment by r3lays** [comment]
Here's a request flow that recently happened to me.
As you can see the initial requests with offset=-1 seem to work as expected. Then as you can see below the very next requests fail with params similar to: `api/electric/events?offset=0_0&handle=27986206-1731475679263`

However as far as we can tell from the replay, it did recover and load the data in. 

![Screenshot 2024-11-13 at 8 20 29 AM](https://github.com/user-attachments/assets/de715d50-d006-46bf-b29c-02ca1b6230bb)

**Comment by msfstef** [comment]
I mean the electric sync image - our latest is on `0.8.1`

**Comment by KyleAMathews** [comment]
ah wait — @r3lays does your proxy add the shape definition on every request back to Electric?

**Comment by r3lays** [comment]
Hmm I believe it does - can you elaborate? 

We have a piece of code that attaches our where clause on the proxy.

**Comment by KyleAMathews** [comment]
@r3lays just that the error might actually be correct — if you don't apply the where clause consistently then it does break things with this error.

**Comment by r3lays** [comment]
I see. As I mentioned before, the only time we attach a where clause is in the proxy and that attaches our team id.

Previously I was attempting to use the where clause but never in preview only in dev.

**Comment by r3lays** [comment]
> I mean the electric sync image - our latest is on `0.8.1`

We are using latest, just confirmed.

**Comment by KyleAMathews** [comment]
@r3lays could you post your proxy code here (minus any internal bits) for us to look at?

**Comment by r3lays** [comment]
```go
package electric
import (
	"errors"
	"fmt"
	"github.com/KPX-Software/db/team"
	"github.com/KPX-Software/http"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/utils"
	"io"
	"net/url"
	"os"
)
func electricForwarder(ctx *fiber.Ctx) error {
	rawRequestUrl := utils.CopyString(ctx.OriginalURL())
	requestUrl, err := url.Parse(rawRequestUrl)
	if err != nil {
		return err
	}
	newBaseUrl := os.Getenv("ELECTRIC_API_URL")

	newBaseUrl += "v1/shape?"
	values := url.Values{}
	for name, vals := range requestUrl.Query() {
		for _, val := range vals {
			values.Add(name, val)
		}
	}
	orgId, ok := ctx.Locals("orgId").(string)
	if !ok {
		return errors.New("no org id")
	} else if orgId == "" {
		return errors.New("invalid org id")
	}
	dbTeam, err := team.GetTeamByClerkOrgId(orgId)
	if err != nil {
		return err
	}
	newWhereClause := fmt.Sprintf("team_id = '%s'", dbTeam.GetId())
	values.Set("where", newWhereClause)
	finalURL := newBaseUrl + values.Encode()
	fmt.Println(finalURL)
	req, err := http.NewRequest("GET", finalURL, nil)
	req.Header = map[string][]string{
	// sec. stuff
	}
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	b, err := io.ReadAll(res.Body)
	if err != nil {
		res.Body.Close()
		return err
	}
	res.Body.Close()
	ctx.Status(res.StatusCode)
	for k, vals := range res.Header {
		for _, v := range vals {
			ctx.Response().Header.Set(k, v)
		}
	}
	if res.Header.Get("content-encoding") != "" {
		ctx.Response().Header.Del("content-encoding")
		ctx.Response().Header.Del("content-length")
	}
	return ctx.Send(b)
}
```

**Comment by KyleAMathews** [comment]
Hmm yeah that looks fine (as far as I can read Go code anyways). So probably not the proxy.

**Comment by KyleAMathews** [comment]
Oh actually on issue — it looks like from your screenshot that table is a path parameter and not a query parameter? E.g. `/v1/shape/my-table` should be `/v1/shape?table=my-table`

**Comment by r3lays** [comment]
Yeah that was something we had and then changed yesterday as well. 

It now should be sending it as a query parameter.

**Comment by KyleAMathews** [comment]
ok — you said I think that you also had nginx or something in there as well? Did you restart everything to clear any caches? Have you seen any issues today?

**Comment by r3lays** [comment]
Resolved this issue - was on my end. Had a conflicting shape stream that was being called somewhere. 

Appreciate the help!
