### ISSUE TITLE
Elixir client cannot point to arbitrary proxy

### ISSUE THREAD

**Issue by msfstef** [electric-sql/electric#1992]
The Elixir client currently hardcodes the path of the shape API to be appended to the base URL provided, which (unless I'm missing something?) makes it impossible to point it to an arbitrary proxy:

https://github.com/electric-sql/electric/blob/f1e7d702e9649160e1e01290dd30e3017bf3b70b/packages/elixir-client/lib/electric/client/fetch/request.ex#L81-L82

Perhaps rather than providing a base URL it should accept the actual endpoint for the shape API itself.

Tagging @magnetised for confirmation

**Comment by magnetised** [comment]
Good point. I hated making the user know our api endpoint path, seemed fragile and cumbersome, but I see the need for flexibility. Will tackle asap

**Comment by magnetised** [comment]
@msfstef https://github.com/electric-sql/electric/pull/1994
