### ISSUE TITLE
Track replication lag in otel metrics and log warning when it gets too high

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#2031]
We really need visibility into this.

**Comment by balegas** [comment]
Why not do both? I think it is useful to know the amount of bytes that are pending in the WAL and what is the latency for electric to write a transaction into the log

**Comment by KyleAMathews** [comment]
Yeah both sound great. I didn't know we could get the actual time diff so didn't mention it but that'd be great to have as well.

Yeah warnings from your otel collector is a lot more flexible — people can already set warnings from postgres data directly. We can potentially add warnings directly in the Electric logs as well but a good sequencing of work is to first gather the data and then later decide exactly how to communicate it.
