### ISSUE TITLE
Order params in the query strings for the clients we maintain

### ISSUE THREAD

**Issue by balegas** [electric-sql/electric#2041]
Cloudflare (and potentially other CDNs) do not threat query string independently of the param order, which will result in cache misses if different clients are building the query strings with the params in different order.

We should ensure that our client set URL query parameters in a consistent order, e.g. by ordering them.

- [ ] add a note about this in our dcos

**Comment by msfstef** [comment]
Opened https://github.com/electric-sql/electric/pull/2044 to address this - not sure what the note in the docs should be and where?
