### ISSUE TITLE
Remove `decode_message` span

### ISSUE THREAD

**Issue by balegas** [electric-sql/electric#2078]
Remove `decode_message` span and store decode execution time into parent span. so we later can find outliers.

We currently create a `decode_message` span for every transaction we handle, which is generating loads of spans

**Comment by kevin-dp** [comment]
I'm wondering whether we want to add this as span attributes or events.
Here's an explanation on when to use attributes vs events: https://opentelemetry.io/docs/concepts/signals/traces/#when-to-use-span-events-versus-span-attributes

It would make sense to me to add an event at the start of decoding the message and an event at the end of the decoding and from those timestamps we could compute the duration. Or we could just add it as an attribute as suggested in this issue. Not sure what's best.

**Comment by balegas** [comment]
Sounds good to me, but cc.ing @KyleAMathews who has more experience with OTEL.
