### ISSUE TITLE
[VAX-971] client: Leaky resources (Notifier subscriptions, EventEmitter listeners...)

### ISSUE THREAD

**Issue by davidmartos96** [electric-sql/electric#243]
Here I list some places in the client code which leak subscriptions to the notifier, as they are never cleared up. These are the ones we found while working on the Dart client.

- [x] `ElectricNamespace` 
https://github.com/electric-sql/electric/blob/23e6ff1bff414c4bb38d660cc4faf22742ce62b5/clients/typescript/src/electric/namespace.ts#L18
Would it make sense to have a `dispose`/`close` method in the `ElectricClient` class? It wouldn't close the database connection, but it would clean up internal resources used by Electric.

- [x] `Client` listeners https://github.com/electric-sql/electric/blob/1b24995731a663661064bf478bb73da8560168f7/clients/typescript/src/satellite/process.ts#L342
Those listeners are not cleaned up individually nor by calling `removeAllListeners` on the `EventEmitter`.

- [x] `AuthState` changes https://github.com/electric-sql/electric/blob/23e6ff1bff414c4bb38d660cc4faf22742ce62b5/clients/typescript/src/satellite/process.ts#L188
Possible solution: Since the subscription id is being reused, maybe there could be a `dispose` method in the `Satellite` interface.

- [x] `ConnectivityState` changes https://github.com/electric-sql/electric/blob/23e6ff1bff414c4bb38d660cc4faf22742ce62b5/clients/typescript/src/satellite/process.ts#L204
Possible solution: Unsubscribe in the `stop` method.

- [x] Throttle snapshot https://github.com/electric-sql/electric/blob/23e6ff1bff414c4bb38d660cc4faf22742ce62b5/clients/typescript/src/satellite/process.ts#L151
`lodash` throttle output has a method cancel.
Possible solution: Instantiate the throttle in the `start` method and clean it up in `stop`

<sub>[VAX-971](https://linear.app/electric-sql/issue/VAX-971/client-leaky-resources-notifier-subscriptions-eventemitter-listeners)</sub>

**Comment by balegas** [comment]
Hei, we’ll look into this and report here

**Comment by davidmartos96** [comment]
Another design question. Should the ElectricClient/Namespace `close` also close the Satellite process from the registry? Or is it something that the user would need to call additionally?

**Comment by balegas** [comment]
I think close would be a destructive call and self-deregister from the registry.
I haven't yet got my head in the space for working on this, but is on my list :)

**Comment by balegas** [comment]
This patch [https://github.com/electric-sql/electric/pull/548](https://github.com/electric-sql/electric/pull/548) ticks the second box.

**Comment by balegas** [comment]
I think we should expose an unelectrify function to clear the database file (optional) and de-register from the Registry.

**Comment by balegas** [comment]
Also see this comment [https://github.com/electric-sql/electric/pull/548](https://github.com/electric-sql/electric/pull/548)

**Comment by kevin-dp** [comment]
PR https://github.com/electric-sql/electric/pull/703 ticks the first box and adds a unit test to check that all listeners are disposed when closing the Electric client.

**Comment by davidmartos96** [comment]
I guess this could be closed now that all is merged.
Thank you! :smile:
