### ISSUE TITLE
expo-sqlite type issue 

### ISSUE THREAD

**Issue by isaporiti** [electric-sql/electric#248]
When running the `typecheck` node task, I get the following error: 
```
test/example-typing-usage/expo-sqlite.ts:14:32 - error TS2345: Argument of type 'SQLiteDatabase' is not assignable to parameter of type 'Database'.
  Type 'SQLiteDatabase' is not assignable to type 'WebSQLDatabase & { _name?: string | undefined; }'.
    Type 'SQLiteDatabase' is missing the following properties from type 'WebSQLDatabase': version, transaction, readTransaction
```
This happens in the [expo-sqlite example](https://github.com/electric-sql/electric/blob/main/clients/typescript/test/example-typing-usage/expo-sqlite.ts#L14) because [`electrify`](https://github.com/electric-sql/electric/blob/main/clients/typescript/src/drivers/expo-sqlite/index.ts#L37) expects an implementation of either `Database` or `WebSQLDatabase` interfaces from `expo-sqlite`.

Even if `expo-sqlite` does [declare and export a `Database` interface](https://github.com/expo/expo/blob/main/packages/expo-sqlite/src/SQLite.types.ts#L27), their [`openDatabase` function returns an instance of `SQLiteDatabase`](https://github.com/expo/expo/blob/main/packages/expo-sqlite/src/SQLite.ts#L171), which doesn't implement it. 

I see that this `electrify` is [tested with a mock implementation of `Database`](https://github.com/electric-sql/electric/blob/main/clients/typescript/src/drivers/expo-sqlite/mock.ts#L17). Did you have this type mismatch in mind when running this specific case?

**Comment by icehaunter** [comment]
Hello @isaporiti! Thanks for the report. We'll look into this, likely early next week. It's a little weird you're getting this error on our codebase, given that the `typecheck` task is ran on `main` and on every PR and is green: https://github.com/electric-sql/electric/actions/runs/5541123991/jobs/10114120291

Did you install deps as in `pnpm install --frozen-lockfile`? Maybe something got updated (again :upside_down_face:) and broke the types?

**Comment by isaporiti** [comment]
Hi @icehaunter ! Thank you for the prompt response. I actually had installed dependencies with npm, and it seems I had another version of expo-sqlite with it. Installing dependencies again with `pnpm` as you indicate solved it.
Thank you again!
