### ISSUE TITLE
[client] _getMeta wrong typings

### ISSUE THREAD

**Issue by js2702** [electric-sql/electric#259]
After some recent changes, there is a call on _setMetaStatement with the value null.

https://github.com/electric-sql/electric/blob/8f68c1b49c78909ef1355dadbf16c9a320bb2e23/clients/typescript/src/satellite/process.ts#L443C40-L443C40 

But at the same time getMeta returns string and not string|null. Wouldn't this need to be changed to string|null? And maybe _setMetaStatement could receive string|null instead of SqlValue.

**Comment by klavinski** [comment]
Hello, I wanted to familiarise myself with the codebase, and picked this issue to see if I can help.

The typing is indeed incorrect, but this precise case should not throw an error:

```typescript
const lsnBase64 = await this._getMeta('lsn')
    if (lsnBase64 && lsnBase64.length > 0) {
      this._lsn = base64.toBytes(lsnBase64)
      Log.info(`retrieved lsn ${this._lsn}`)
    } else {
      Log.info(`no lsn retrieved from store`)
    }
```
It is the only place where `lsn` is retrieved. One solution, if we wanted to limit type assertions (which may become incorrect in the case of a change), is to hard-code the entries:

```typescript
type Uuid = `${string}-${string}-${string}-${string}-${string}`

type MetaEntries = {
  clientId: Uuid | '',
  compensations: number,
  lastAckdRowId: `${ number }`,
  lastSentRowId: `${ number }`,
  lsn: string | null,
  subscriptions: string,
}
```

There would be just one source of truth for them. Then, we would set this type signature for the arguments of `_setMeta`(`Statement`):
```typescript
<K extends keyof MetaEntries | Uuid>(key: K, value: K extends keyof MetaEntries ? MetaEntries[K] : string | null)
```
And `_getMeta` becomes (I only changed the types):

```typescript
async _getMeta<K extends keyof MetaEntries | Uuid>(key: K) {
    const meta = this.opts.metaTable.toString()

    const sql = `SELECT value from ${meta} WHERE key = ?`
    const args = [key]
    const rows = await this.adapter.query({ sql, args })

    if (rows.length !== 1) {
      throw `Invalid metadata table: missing ${key}`
    }

    return rows[0].value as K extends keyof MetaEntries ? MetaEntries[K] : string | null
  }
```

Finally, we can type `_getClientId` thus:

```typescript
private async _getClientId(): Promise<Uuid> {
    const clientIdKey = 'clientId'

    let clientId = await this._getMeta(clientIdKey) as Uuid | ''

    if (clientId === '') {
      clientId = uuid() as Uuid
      await this._setMeta(clientIdKey, clientId)
    }
    return clientId
  }
```

No more type errors. We can now write with confidence lines like:

```typescript
    this._lastAckdRowId = Number(await this._getMeta('lastAckdRowId'))
    this._lastSentRowId = Number(await this._getMeta('lastSentRowId'))
```
I only did a superficial reading so far, so I hope I made no mistakes and that these suggestions might be useful!

**Comment by icehaunter** [comment]
@klavinski, thanks for the breakdown! Your suggestions seem reasonable to me, with only caveat that I much prefer explicit return types to inferred (for `_getMeta` function). I'll be happy to see a PR if you'd like to contribute!

**Comment by klavinski** [comment]
Thank you for your comment! The point of typing the return of `_getMeta` was to get the exact type inferred when using these methods, for example:
<img width="466" alt="image" src="https://github.com/electric-sql/electric/assets/28248193/28c5a2a2-2a64-4637-9113-1c167b4cb4aa">

Here, you can be sure `Number(await this._getMeta('lastAckdRowId'))` will always succeed. I completely understand your point (I too prefer inferring types), do you see a way to avoid having to assert the return type?
