### ISSUE TITLE
[VAX-1003] create-electric-app with asdf node

### ISSUE THREAD

**Issue by AntonOfTheWoods** [electric-sql/electric#422]
```bash
anton@zub:~/dev/ntc$ node --version
v18.17.0 
--> same problem with 20.6.1
anton@zub:~/dev/ntc$ which node
/home/anton/.asdf/shims/node
anton@zub:~/dev/ntc$ npx create-electric-app ques
/usr/bin/env: ‘node --no-warnings’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```

Should this work?

<sub>[VAX-1003](https://linear.app/electric-sql/issue/VAX-1003/create-electric-app-with-asdf-node)</sub>

**Comment by thruflo** [comment]
This should work. @kevin-dp can you take a look?

**Comment by kevin-dp** [comment]
Looks similar to this issue: [https://github.com/sakuli/sakuli/issues/127](https://github.com/sakuli/sakuli/issues/127).

> Unfortunately, not every implementation of env splits the argument string, which is causing the mentioned problem in the first place.

So, i'm assuming the problem comes from the --no-warnings flag here:
[https://github.com/electric-sql/electric/blob/main/examples/starter/src/index.ts#L1](https://github.com/electric-sql/electric/blob/main/examples/starter/src/index.ts#L1)

Could you try to clone this repo and remove the `--no-warnings` flag from the file above.
Then locally publish the package:
```
# at root of the project
pnpm install
cd examples/starter
pnpm install & pnpm build
# now install create-electric-app locally
npm link
```

Now, let's try again (without `npx`):
```
create-electric-app ques
```

**Comment by AntonOfTheWoods** [comment]
Yep, that works. I'm using Ubuntu 22.04.

**Comment by kevin-dp** [comment]
Great, thanks for confirming!
We will publish the fix shortly.

**Comment by kevin-dp** [comment]
The path seems correct. Can you double check that the file exists `"/home/anton/dev/ntc/ques/node_modules/@electric-sql/prisma-generator/dist/bin.js"`. If it exists it could be a related problem but with the `prisma generate` command. We are considering publishing our Prisma generator such that we don't have to link to that file, that might solve the problem.

**Comment by kevin-dp** [comment]
Right, that explains it. Thanks for your feedback, will flag it up for someone to look at it.

**Comment by balegas** [comment]
When working on this see @kevin's [VAX-999](https://linear.app/electric-sql/issue/VAX-999/publish-generator-as-a-prisma-community-generator)

**Comment by balegas** [comment]
@AntonOfTheWoods let us know if this fixed the issue for you. 
We are not expecting issues fetching wa-sqlite dep.

Please make sure to follow the quickstart steps from scratch and with latest release (0.1.4)

Thanks for identifying the issue.

**Comment by AntonOfTheWoods** [comment]
@balegas , so the other bugs I mentioned here are going to get fixed later? 

I'm still getting:

```
...
➤ YN0000: wa-sqlite@workspace:. STDERR make: emcc: No such file or directory
➤ YN0000: wa-sqlite@workspace:. STDERR make: *** [Makefile:197: tmp/obj/dist/sqlite3.o] Error 127
```

Or do I have some cruft that is messing with things. And did anyone test with a virgin VM? (even arch would be fine...)

**Comment by balegas** [comment]
I see, indeed maybe everyone has installed emcc locally and we need to account for that on the instructions. I'll check that and update instructions.

**Comment by AntonOfTheWoods** [comment]
@balegas again, a blank virtualbox machine that an intern spins up and runs through the basic docs instructions every now and then would avoid a lot of pain for newcomers...

**Comment by kevin-dp** [comment]
@AntonOfTheWoods i used Docker to run ubuntu and after installing nodejs, npm, etc. it worked fine for me.
An easier way to test it is:
```
docker run -it node /bin/bash
npx create-electric-app foo 
```
The above works fine for me.

**Comment by AntonOfTheWoods** [comment]
@kevin-dp , so something is wrong with my setup, and it shouldn't be needing `emsdk`?

**Comment by kevin-dp** [comment]
> @kevin-dp , so something is wrong with my setup, and it shouldn't be needing `emsdk`?

Hard to tell what's wrong here. I've not been able to reproduce the problem on mac or linux.

**Comment by thruflo** [comment]
No. The only reason I can think of is if the `wa-sqlite` dependency is building from source. Which it shouldn't because it comes with pre-built binaries. Perhaps the pre-built binaries don't match your environment somehow?

**Comment by AntonOfTheWoods** [comment]
Yeah, no idea whats going on here - must be an env var that's messing with something somewhere. Same diff with `PUPPETEER_SKIP_DOWNLOAD` I guess. I just checked on a fresh VM and it says something about dependencies not installing correctly but it still produced a starter project. Looks like it's just me!

**Comment by balegas** [comment]
This is merged in PR-435
