### ISSUE TITLE
[VAX-1004] Supported dev OSes

### ISSUE THREAD

**Issue by AntonOfTheWoods** [electric-sql/electric#424]
Given the wide usage of Ubuntu 22.04, it would seem a reasonable dev system to work with. Are you guys all working/testing on MacOS or something? Several steps in the quickstart just seem to fail, and trying to hack around them requires installing and sourcing an `emsdk`, installing `node_modules` with `PUPPETEER_SKIP_DOWNLOAD=true npm i @electric-sql/prisma-generator`, doing `yarn install`, etc. - all things not listed at all in the quickstart.

I realise things are moving fast, but a quick test in a fresh Ubuntu 22.04 VM for the quickstart seems pretty reasonable to me... The issue being, it is very much not "quick" to get started, and wouldn't be possible for someone who hasn't spent a lot of time trying to get things working.

<sub>[VAX-1004](https://linear.app/electric-sql/issue/VAX-1004/supported-dev-oses)</sub>

**Comment by thruflo** [comment]
Hey, absolutely, the quickstart should work on Ubuntu.

As it happens we’re half osx half arch linux. We test on Ubuntu but from the sounds of it we may not have tested some of the manual steps or may have an unrepresentative environment.

**Comment by balegas** [comment]
We fixed the issues with flag on ubuntu; but then was something weird.
