### ISSUE TITLE
[VAX-965] Modify generator to introspect PG DB

### ISSUE THREAD

**Issue by kevin-dp** [electric-sql/electric#437]
Currently, the generator fetches all SQLite migrations from Electric, constructs a SQLite DB, and introspects it in order to generate a Prisma schema and Zod schemas. However, by going from a PG DB to a SQLite DB we lose information about the original types of columns in the PG DB.

In order not to lose information about the original PG schema, we need to modify the generator to introspect the PG database or a copy of it such that the generated Prisma schema and Zod schemas reflect the original PG types. Then, the DAL can do the conversion of PG values to SQLite values when storing them and do the opposite conversion from SQLite values to PG values when reading.

<sub>From [SyncLinear.com](https://synclinear.com) | [VAX-965](https://linear.app/electric-sql/issue/VAX-965/modify-generator-to-introspect-pg-db)</sub>

**Comment by js2702** [comment]
I'm guessing one of the reasons is the timestamp data type in Postgresql. Are you planning to make the DAL client work with Date objects in Javascript? And convert them to text internally? We are having the same discussion for the Dart client. Ideally to prevent the user inserting a non date string into the sqlite.

**Comment by alco** [comment]
@js2702 Yes, we're adding support for date, time, timestamp, and timestamptz types to DAL. They will all be stored as TEXT in SQLite and converted to/from the JS `Date` object.

Example values in SQLite:
* `date`: `2023-08-24`
* `time`: `17:48:51.122`
* `timestamp`: `2023-08-24 17:48:52`
* `timestamptz`: `2023-08-24 17:48.53.000009Z`

**Comment by js2702** [comment]
So when storing that timestamp, without the Z for UTC, would dates be treated always as UTC in the DAL? Or would this case be treated as local time?

**Comment by tyrauber** [comment]
hey @kevin-dp, are you familiar with [postgraphile](https://www.graphile.org/postgraphile/security/)? There is a lot of similarity between projects I think, specifically in regards to JWT and RLS usage in postgres.  Postgraphile uses [pg-introspection](https://github.com/graphile/crystal/tree/main/utils/pg-introspection]) to do [a sql introspection query](https://github.com/graphile/crystal/blob/f649319a6fcc02eea3ca53097abfa29c27dc02df/utils/pg-introspection/src/introspection.ts#L1431C1-L1622) that generates the graphql schema used in graphiql.  Perhaps, electric-sql could do something similar?

**Comment by kevin-dp** [comment]
> hey @kevin-dp, are you familiar with [postgraphile](https://www.graphile.org/postgraphile/security/)? There is a lot of similarity between projects I think, specifically in regards to JWT and RLS usage in postgres. Postgraphile uses [pg-introspection](https://github.com/graphile/crystal/tree/main/utils/pg-introspection%5D) to do [a sql introspection query](https://github.com/graphile/crystal/blob/f649319a6fcc02eea3ca53097abfa29c27dc02df/utils/pg-introspection/src/introspection.ts#L1431C1-L1622) that generates the graphql schema used in graphiql. Perhaps, electric-sql could do something similar?

Hi @tyrauber, just noticing your comment now. Interesting, will definitely flag it up for consideration. Thanks!
