### ISSUE TITLE
electric-sql/* Typescript Path Alias

### ISSUE THREAD

**Issue by tyrauber** [electric-sql/electric#475]
Instead of resolving the modules by hardcoding paths in metro.config.js:

https://github.com/electric-sql/electric/blob/4682c4aea72964c5240dcbe9dfd4ba88d201a6a3/examples/expo/metro.config.js#L5-L38

Is there any reason we don't just use a typescript path alias?

```
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "jsx": "react",
    "strict": true,
    "paths": {
      "electric-sql/*": ["../../node_modules/electric-sql/dist/*"],
    }
  },
}
```

And then in the client:

```
import { electrify } from 'electric-sql/drivers/expo-sqlite'
import { makeElectricContext, useLiveQuery } from 'electric-sql/frameworks/react/'
import { genUUID } from 'electric-sql/util'
```

Seems like a cleaner approach?

**Comment by kevin-dp** [comment]
Hi @tyrauber,
The solution you propose would indeed simplify the metro configuration.
However, it would make the imports a bit longer and more convoluted.
I prefer exposing a clean module name and mapping it to the corresponding file such that internally we can organize our project how we want.
