### ISSUE TITLE
[VAX-1068] Prefix env var DATABASE_URL

### ISSUE THREAD

**Issue by balegas** [electric-sql/electric#480]
The starter template uses an env var named DATABASE_URL that sets the URL for connecting to Postgres.

The name of this variable might easily clash with env vars of other projects. The goal of this task is to prefix that variable with ELECTRIC\_.

<sub>From [SyncLinear.com](https://synclinear.com) | [VAX-1068](https://linear.app/electric-sql/issue/VAX-1068/prefix-env-var-database-url)</sub>

**Comment by KhurramJalil** [comment]
Fixed by PR https://github.com/electric-sql/electric/pull/482

**Comment by balegas** [comment]
Will merge it after testing it. Thanks.
