### ISSUE TITLE
[VAX-1069] Output info about pg connection url when running starter scripts

### ISSUE THREAD

**Issue by balegas** [electric-sql/electric#481]
The Postgres connection URL can be configured using an environment variable (DATABASE_URL). When working with multiple shells to interact with Electric, it's easy to overlook setting the variable in some of the shells.

The minimal patch would be to raise that the script is not using the default DATABASE_URL. "Ideally, it should display the URL details while obfuscating the password.

Note: Issue #480 is concerned with renaming DATABASE_URL to ELECTRIC_DATABASE_URL

<sub>From [SyncLinear.com](https://synclinear.com) | [VAX-1069](https://linear.app/electric-sql/issue/VAX-1069/output-info-about-pg-connection-url-when-running-starter-scripts)</sub>

**Comment by balegas** [comment]
Check this is done in [VAX-1087](https://linear.app/electric-sql/issue/VAX-1087/prefix-starter-template-container-name-with-app-name)

**Comment by kevin-dp** [comment]
Closing this as this has been implemented in #505.
`yarn db:migrate` and `yarn db:psql` now output the connection url without disclosing the username or password.

**Comment by alco** [comment]
Reopened by accident.
