### ISSUE TITLE
Client unable to sync up local writes to boolean or float columns

### ISSUE THREAD

**Issue by alco** [electric-sql/electric#507]
This is a known issue that will be addressed in one of the upcoming patch releases.

The problem happens for tables that are electrified and then included in the client as a bundled migration by running `yarn db:migrate` or `npx electric-sql generate`, depending on your setup.

When a new record with a boolean column is then created on the client, it will break the replication stream such that no further local writes will be able to sync up. A workaround for testing sync with boolean columns is to electrify a table in Postgres and then use `electric.db.sql.raw({sql: "INSERT ... INTO ...", args: [...]})`.

For float columns, the same error state is reached when trying to sync up a whole number, i.e. one that does not have any places after the decimal point. There's no workaround for this issue but we're working on releasing a fix soon.

Related to VAX-842 and VAX-1078.

**Comment by gorbak25** [comment]
@alco We had this issue and we also were attributing this issue to floats. The problem is not with floats but with CamelCased columns. A table with a float column named "asdf" will work fine but a table with a "CreatedAt" float column fails to sync to postgres.

**Comment by balegas** [comment]
@alco can we close this issue after your changes?

**Comment by alco** [comment]
@balegas booleans still aren't working.

**Comment by alco** [comment]
This has been fixed in version 0.7.0.
