### ISSUE TITLE
Problems with nested creates in the Prisma client

### ISSUE THREAD

**Issue by ccapndave** [electric-sql/electric#528]
Hi!  I am a having some problems with relational data and the generated Prisma client.  I'm trying to model a graph structure with vertices and edges, so I've started with this Prisma migration:

```prisma
model Vertex {
  id   String @id

  edgesIn  Edge[] @relation("toVertex")
  edgesOut Edge[] @relation("fromVertex")
}

model Edge {
  id         String @id

  fromVertex   Vertex @relation("fromVertex", fields: [fromVertexId], references: [id])
  fromVertexId String

  toVertex   Vertex @relation("toVertex", fields: [toVertexId], references: [id])
  toVertexId String
}
```

which generates the following SQL:

```sql
-- CreateTable
CREATE TABLE "Vertex" (
    "id" TEXT NOT NULL,
    CONSTRAINT "Vertex_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Edge" (
    "id" TEXT NOT NULL,
    "fromVertexId" TEXT NOT NULL,
    "toVertexId" TEXT NOT NULL,
    CONSTRAINT "Edge_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Edge" ADD CONSTRAINT "Edge_fromVertexId_fkey" FOREIGN KEY ("fromVertexId") REFERENCES "Vertex"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Edge" ADD CONSTRAINT "Edge_toVertexId_fkey" FOREIGN KEY ("toVertexId") REFERENCES "Vertex"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


/* ⚡ Electrify (added manually) ⚡ */
CALL electric.electrify('Vertex');
CALL electric.electrify('Edge');
```

I then call `npx electric-sql generate` to generate the Prisma client.  I can take a look in `node_modules/.prisma/client/schema.prisma` to see what schema was inferred, and it came up with the following:

```prisma
model Vertex {
  @@map("Vertex")
  id                             String @id
  Edge_Edge_toVertexIdToVertex   Edge[] @relation("Edge_toVertexIdToVertex")
  Edge_Edge_fromVertexIdToVertex Edge[] @relation("Edge_fromVertexIdToVertex")
}

model Edge {
  @@map("Edge")
  id                               String @id
  fromVertexId                     String
  toVertexId                       String
  Vertex_Edge_toVertexIdToVertex   Vertex @relation("Edge_toVertexIdToVertex", fields: [toVertexId], references: [id])
  Vertex_Edge_fromVertexIdToVertex Vertex @relation("Edge_fromVertexIdToVertex", fields: [fromVertexId], references: [id])
}
```

So the generator has made the following name changes compared to the original schema:

- `Vertex.edgesIn`  => `Vertex.Edge_Edge_toVertexIdToVertex`
- `Vertex.edgesOut` => `Vertex.Edge_Edge_fromVertexIdToVertex`
- `Edge.fromVertex` => `Edge.Vertex_Edge_fromVertexIdToVertex`
- `Edge.toVertex`   => `Edge.Vertex_Edge_toVertexIdToVertex`

Now that I have a client, I am trying to work with the Prisma API in a few different situations:

## Create a vertex linked to another vertex with an edge

Here I'm trying to do a nested create starting with the root vertex, and creating an edge linked to another vertex:

```ts
await electric.db.Vertex.create({
  data: {
    id: "vertex-1",
    Edge_Edge_fromVertexIdToVertex: {
      create: {
        id: "edge-1",
        Vertex_Edge_toVertexIdToVertex: {
          create: {
            id: "vertex-2",
          }
        }
      }
    }
  }
});
```

This fails with the following zod error:

```
index.mjs:538 Uncaught (in promise) ZodError: [
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "object",
            "received": "undefined",
            "path": [
              "data",
              "Vertex_Edge_fromVertexIdToVertex"
            ],
            "message": "Required"
          },
          {
            "code": "unrecognized_keys",
            "keys": [
              "fromVertexId"
            ],
            "path": [
              "data"
            ],
            "message": "Unrecognized key(s) in object: 'fromVertexId'"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "string",
            "received": "undefined",
            "path": [
              "data",
              "toVertexId"
            ],
            "message": "Required"
          },
          {
            "code": "unrecognized_keys",
            "keys": [
              "Vertex_Edge_toVertexIdToVertex"
            ],
            "path": [
              "data"
            ],
            "message": "Unrecognized key(s) in object: 'Vertex_Edge_toVertexIdToVertex'"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [
      "data"
    ],
    "message": "Invalid input"
  }
]
```

From the look of the error, it seems that zod is both unhappy that `Vertex_Edge_fromVertexIdToVertex` hasn't been explicitly specified, and is also unhappy about `Vertex_Edge_toVertexIdToVertex` in the nested vertex.  As far as I can tell, the Prisma docs seem to suggest that this should work.

Note that if I do the same thing, but starting from the edge it works correctly:

```ts
await electric.db.Edge.create({
  data: {
    id: "edge-1",
    Vertex_Edge_fromVertexIdToVertex: {
      create: {
        id: "vertex-1",
      }
    },
    Vertex_Edge_toVertexIdToVertex: {
      create: {
        id: "vertex-2",
      }
    }
  }
});
```

## Create a vertex linked to an existing vertex with an edge

Now that I have two vertices linked with an edge, I want to attach a new vertex via a new edge.

```ts
await electric.db.Edge.create({
  data: {
    id: "edge-2",
    fromVertexId: "vertex-2",
    Vertex_Edge_toVertexIdToVertex: {
      create: {
        id: "vertex-3",
      }
    }
  }
});
```

This fails with the same error as my `create` query.

```
Uncaught ZodError: [
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "object",
            "received": "undefined",
            "path": [
              "data",
              "Vertex_Edge_fromVertexIdToVertex"
            ],
            "message": "Required"
          },
          {
            "code": "unrecognized_keys",
            "keys": [
              "fromVertexId"
            ],
            "path": [
              "data"
            ],
            "message": "Unrecognized key(s) in object: 'fromVertexId'"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "string",
            "received": "undefined",
            "path": [
              "data",
              "toVertexId"
            ],
            "message": "Required"
          },
          {
            "code": "unrecognized_keys",
            "keys": [
              "Vertex_Edge_toVertexIdToVertex"
            ],
            "path": [
              "data"
            ],
            "message": "Unrecognized key(s) in object: 'Vertex_Edge_toVertexIdToVertex'"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [
      "data"
    ],
    "message": "Invalid input"
  }
]
```

Other attempts to do this also failed.

Apologies for the wall of text, and any advice would be very gratefully received!

**Comment by kevin-dp** [comment]
Hi @ccapndave 

Since the two errors are similar, I'm going to answer based on your last example where you create the Edge, which is a bit easier to reason about:

```
await electric.db.Edge.create({
  data: {
    id: "edge-2",
    fromVertexId: "vertex-2",
    Vertex_Edge_toVertexIdToVertex: {
      create: {
        id: "vertex-3",
      }
    }
  }
});
```

The problem with this code is that you are mixing the way how you provide the from and to vertex IDs.
For the from vertex id you provide it directly as a string value using the `fromVertexId` property, but for the to vertex id you use a nested create:
```
Vertex_Edge_toVertexIdToVertex: {
  create: {
    id: "vertex-3",
  }
}
```

I believe Prisma does not support mixing both approaches and requires you to either provide them both as strings or both using nested creates. See here the relevant type that i extracted from the generated Prisma client:

```
create<T extends EdgeCreateArgs>(
  args: SelectSubset<T, EdgeCreateArgs>
): Prisma__EdgeClient<EdgeGetPayload<T>>

export type EdgeCreateArgs = {
  // ...
  data: XOR<EdgeCreateInput, EdgeUncheckedCreateInput>
}

export type EdgeCreateInput = {
  id: string
  Vertex_Edge_toVertexIdToVertex: VertexCreateNestedOneWithoutEdge_Edge_toVertexIdToVertexInput
  Vertex_Edge_fromVertexIdToVertex: VertexCreateNestedOneWithoutEdge_Edge_fromVertexIdToVertexInput
}

export type EdgeUncheckedCreateInput = {
  id: string
  fromVertexId: string
  toVertexId: string
}
```

Note the type of `EdgeCreateInput` and `EdgeUncheckedCreateInput`. You have to obey one of those types but can't provide a mix of them.

Let me know if this solves your problem then i can close this issue.

**Comment by ccapndave** [comment]
Yup, understood (although it would be really nice if, when using Prisma migrations, there was a way to "keep" the original Prisma schema so that the names stayed the same).

You are right!  When using just ids or `create` things work as expected.

Therefore that brings me onto my next question; since this restriction means we aren't going to be able to write a graph in a single single Prisma `create`, is there some other way to run creates in a transaction?  Otherwise if writing a subgraph fails we're going to end up with half a graph in the db.

As an aside, if we were to scrap Prisma altogether and use `db.raw` with straight SQL, could we use `BEGIN` and `COMMIT`/`ROLLBACK`?  Are there other disadvantages to doing it this way?

**Comment by ccapndave** [comment]
Or actually, can I just do a whole bunch of semicolon separates `INSERT INTO` statements in a single `db.raw` and have them in a transaction that way?

**Comment by kevin-dp** [comment]
@ccapndave sorry i missed your new questions.
As you discovered, `db.raw` will also wrap your raw query in a transaction so that won't work.
However, on the electrified DB you can directly access the database adapter which has `runInTransaction` and `transaction` methods which allow you to run several queries within a transaction.

Here is an example for the less obvious `transaction` method:
```
const electric = await electrify(conn, schema, config)
const deleteResult = await electric.adapter.transaction((tx, setResult) => {
  tx.query({ sql: 'SELECT value FROM items' }, (tx2, selectResult) => {
    tx2.run({
      sql: 'DELETE FROM items WHERE value = ?',
      args: [selectResult[0]?.value]
    }, (_tx3, deleteResult) => {
      setResult(deleteResult)
    })
  })
})
```
