### ISSUE TITLE
[VAX-1194] INSERT or REPLACE throwing an unexpected Foreign Key constraint error

### ISSUE THREAD

**Issue by balegas** [electric-sql/electric#540]
Here is how I can reproduce the issue:

```sql
-- CreateTable
CREATE TABLE "Vertex" (
    "id" TEXT NOT NULL,
    "noteHtml" TEXT,

    CONSTRAINT "Vertex_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Edge" (
    "id" TEXT NOT NULL,
    "fromVertexId" TEXT NOT NULL,
    
    CONSTRAINT "Edge_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Edge" ADD CONSTRAINT "Edge_fromVertexId_fkey" FOREIGN KEY ("fromVertexId") REFERENCES "Vertex"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

/* ⚡ Electrify ⚡ */
CALL electric.electrify('Vertex');
CALL electric.electrify('Edge');
```

Then in the client:

```js
await electric.adapter.runInTransaction({ sql: "INSERT OR REPLACE INTO Vertex (id, noteHtml) VALUES (?, ?)", args: [ "vertex-1", "Vertex 1 text" ]});
await electric.adapter.runInTransaction({ sql: "INSERT OR REPLACE INTO Edge (id, fromVertexId) VALUES (?, ?)", args: [ "edge-1", "vertex-1" ]});
await electric.adapter.runInTransaction({ sql: "INSERT OR REPLACE INTO Vertex (id, noteHtml) VALUES (?, ?)", args: [ "vertex-1", "Vertex 1 text changed" ]});

> sqlite-api.js:824 Uncaught Error: FOREIGN KEY constraint failed
```

*Reported by @ccapndave*

<sub>From [SyncLinear.com](https://synclinear.com) | [VAX-1194](https://linear.app/electric-sql/issue/VAX-1194/insert-or-replace-throwing-an-unexpected-foreign-key-constraint-error)</sub>

**Comment by kevin-dp** [comment]
@ccapndave, you reported that the above example did not fail on SQLite directly. But you probably forgot to enable the `FOREIGN_KEYS` pragma. By default it is disabled. This reproduces the error in plain SQLite:

```
PRAGMA foreign_keys = ON;
CREATE TABLE "Vertex" (
    "id" TEXT NOT NULL,
    "noteHtml" TEXT,
    CONSTRAINT "Vertex_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Edge" (
    "id" TEXT NOT NULL,
    "fromVertexId" TEXT NOT NULL,
    CONSTRAINT "Edge_pkey" PRIMARY KEY ("id"),
    FOREIGN KEY ("fromVertexId") REFERENCES "Vertex"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

INSERT OR REPLACE INTO Vertex (id, noteHtml) VALUES ('vertex-1', 'Vertex one text');
INSERT OR REPLACE INTO Edge (id, fromVertexId) VALUES ('edge-1', 'vertex-1');
INSERT OR REPLACE INTO Vertex (id, noteHtml) VALUES ('vertex-1', 'Vertex one text changed');
```

I've digged a bit deeper into this and the error is caused by `ON DELETE RESTRICT`.
It essentially, disallows deleting a parent key if there are one or more child keys mapped to it.
And as you mentioned on Discord, `INSERT OR REPLACE` essentially deletes the row and then inserts it, so the deletion fails because of the FK constraint.

From [the docs](https://www.sqlite.org/foreignkeys.html):
> The "RESTRICT" action means that the application is prohibited from deleting (for ON DELETE RESTRICT) or modifying (for ON UPDATE RESTRICT) a parent key when there exists one or more child keys mapped to it. The difference between the effect of a RESTRICT action and normal foreign key constraint enforcement is that the RESTRICT action processing happens as soon as the field is updated - not at the end of the current statement as it would with an immediate constraint, or at the end of the current transaction as it would with a deferred constraint. Even if the foreign key constraint it is attached to is deferred, configuring a RESTRICT action causes SQLite to return an error immediately if a parent key with dependent child keys is deleted or modified. 

If we remove the `ON DELETE RESTRICT`, SQLite no longer complains:
```
PRAGMA foreign_keys = ON;

CREATE TABLE "Vertex" (
    "id" TEXT NOT NULL,
    "noteHtml" TEXT,
    CONSTRAINT "Vertex_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Edge" (
    "id" TEXT NOT NULL,
    "fromVertexId" TEXT NOT NULL,
    CONSTRAINT "Edge_pkey" PRIMARY KEY ("id"),
    FOREIGN KEY ("fromVertexId") REFERENCES "Vertex"("id") ON UPDATE CASCADE
);

INSERT OR REPLACE INTO Vertex (id, noteHtml) VALUES ('vertex-1', 'Vertex one text');
INSERT OR REPLACE INTO Edge (id, fromVertexId) VALUES ('edge-1', 'vertex-1');
INSERT OR REPLACE INTO Vertex (id, noteHtml) VALUES ('vertex-1', 'Vertex one text changed');
```

**Comment by thruflo** [comment]
Is this not something we should enable by default?

**Comment by balegas** [comment]
We do that by default https://github.com/electric-sql/electric/commit/8f901a25c2937c6221b5b501a489d06e01a16b47

**Comment by ccapndave** [comment]
For anyone else who encounters this problem, a workaround seems to be to add `{ sql: "PRAGMA defer_foreign_keys=true" }` to the beginning of the transaction containing the `INSERT OR REPLACE` statements.

> When the defer_foreign_keys [PRAGMA](https://www.sqlite.org/pragma.html#syntax) is on, enforcement of all [foreign key constraints](https://www.sqlite.org/foreignkeys.html) is delayed until the outermost transaction is committed. The defer_foreign_keys pragma defaults to OFF so that foreign key constraints are only deferred if they are created as "DEFERRABLE INITIALLY DEFERRED". The defer_foreign_keys pragma is automatically switched off at each COMMIT or ROLLBACK. Hence, the defer_foreign_keys pragma must be separately enabled for each transaction. This pragma is only meaningful if foreign key constraints are enabled, of course.

So basically this waits until the end of the transaction to check the foreign keys, by which point they are back in place.
