### ISSUE TITLE
deploying to fly

### ISSUE THREAD

**Issue by spence** [electric-sql/electric#569]
hey guys - awesome tech! 

this was almost exactly what i was looking for (pg interface with a logically-replicated sqlite + crdt on globally distributed instances). i've been playing around with [nqlite](https://github.com/voxoco/nqlite) (nats as a sqlite active-active replicator + yjs), but it's not a robust solution. ideally, i'd like to quickly instantiate many (thousands) of scoped sqlite from pg + replicate crdt-based writes per instance during runtime.

i ran into a few issues deploying electric to fly but ran out of time before i could get things running.

1. `:epgsql.connect` &  ipv6: there's a check for ECTO_IPV6 for the electric endpoints, but on fly, my pg instance is also only available via ipv6.  i added:
```ex
    connection_opts = config
    |> Keyword.fetch!(:connection)
    |> new_map_with_charlists()
    |> set_replication(replication?)
    |> Map.put_new(:tcp_opts, [:inet6])
```

2. composing LOGICAL_PUBLISHER_HOST from fly envs. the ideal hostname is:
```ex
"#{env.FLY_MACHINE_ID}.vm.#{env.FLY_APP_NAME}.internal"
```
but this is a bit tricky to setup since fly config nor fly secrets support interpolating from existing values. i couldn't use `[[processes]]` to inject env vars since dockerfile sets the ENTRYPOINT. i ended up forking electric. 

3. i'm now showing an error i don't quite understand, but this is where i left it
```ex
:error, "55006",
:object_in_use,
"replication slot \"electric_replication_out_test\" is active for PID 22227",
[file: "slot.c", line: "516", routine: "ReplicationSlotAcquire", severity: "ERROR"]
```

cheers

**Comment by alco** [comment]
Hey @spence. Thanks a lot for sharing the info about Fly and your troubleshooting steps! We'll look into  polishing the deployment experience promptly.

Could you elaborate a bit on the second point? Did you fork Electric to make it do the environment variable interpolation in the above string that you're passing to it as a literal `LOGICAL_PUBLISHER_HOST="#{env.FLY_MACHINE_ID}...`?

**Comment by spence** [comment]
@alco yeah exactly:

```ex
  fly_machine_id =
    System.get_env("FLY_MACHINE_ID") ||
      raise("Required environment variable FLY_MACHINE_ID is not set")
  fly_app_name =
    System.get_env("FLY_APP_NAME") ||
      raise("Required environment variable FLY_APP_NAME is not set")
  pg_server_host = "#{fly_machine_id}.vm.#{fly_app_name}.internal"
```
no doubt there's a better solution here, this was just my hack

**Comment by alco** [comment]
Hey @spence.

I was able to reproduce 2 out of 3 issues you had reported.

I've opened a pull request addressing IPv6 support. Electric will be able to work on Fly and have bidirectional connection with Fly Postgres once https://github.com/electric-sql/electric/pull/594 is released.

On the question of setting `LOGICAL_PUBLISHER_HOST` dynamically, there is actually a trick to achieve that without patching Electric. You could build a custom Docker image and set/override any environment variables at runtime, prior to Electric startup, like so:

```
FROM electricsql/electric:0.6.4

RUN echo 'export LOGICAL_PUBLISHER_HOST="$FLY_MACHINE_ID.vm.$FLY_APP_NAME.internal"' >> releases/0.6.4/env.sh
```

The annoying thing about it is that you have to include the release version in the path to `env.sh` that matches the Electric release version in the Docker image. I've flagged it up as issue internally, we'll see if we can come up with something more convenient.

Finally, regarding this error:
```
:error, "55006",
:object_in_use,
"replication slot \"electric_replication_out_test\" is active for PID 22227",
[file: "slot.c", line: "516", routine: "ReplicationSlotAcquire", severity: "ERROR"]
```

I didn't encounter it in my testing but I suspect it could be caused by multiple instances of Electric trying to connect to the same Postgres. Electric creates a subscription, a publication, and a replication slot in Postgres as part of its bootstrap process. You'll need to clean those up before launching Electric with new DB config for things to work properly.

Here's how you can check what's been leftover since your past attempts to run Electric:
```
$ fly pg -a <fly postgres app name> connect

postgres=# select subname, subenabled, subslotname, subpublications, subconninfo from pg_subscription;
  subname   | subenabled | subslotname |    subpublications     |                                           subconninfo                                            
------------+------------+-------------+------------------------+--------------------------------------------------------------------------------------------------
 postgres_1 | t          | postgres_1  | {electric_publication} | host=32874244f30518.vm.alco-fly-test-app.internal port=5433 dbname=electric connect_timeout=5000
(1 row)

```

And here's how you can clean all of that up:
```
postgres=# ALTER SUBSCRIPTION postgres_1 DISABLE; ALTER SUBSCRIPTION postgres_1 SET (slot_name=NONE); DROP SUBSCRIPTION postgres_1;
ALTER SUBSCRIPTION
ALTER SUBSCRIPTION
DROP SUBSCRIPTION

```

**Comment by alco** [comment]
Hey @spence. We have updated the doc for deploying Electric to Fly.io - https://electric-sql.com/docs/integrations/deployment/fly.

Let me recap how to solve all three issues you originally reported:

> 1. `:epgsql.connect` &  ipv6: there's a check for ECTO_IPV6 for the electric endpoints, but on fly, my pg instance is also only available via ipv6

The two configuration options `ELECTRIC_USE_IPV6` and `DATABASE_USE_IPV6` introduced in Electric v0.7.0 solve this.

> 2\. composing LOGICAL_PUBLISHER_HOST from fly envs. the ideal hostname is:
> 
> 
> ```elixir
> "#{env.FLY_MACHINE_ID}.vm.#{env.FLY_APP_NAME}.internal"
> ```

See my previous comment for a possible workaround that works with the official Docker image. Note, however, that with Electric's current requirement that at most one instance can be connected to Postgres at any time, using just the app name in the env var works well enough.

> 3\. i'm now showing an error i don't quite understand, but this is where i left it
> 
> 
> ```elixir
> :error, "55006",
> :object_in_use,
> "replication slot \"electric_replication_out_test\" is active for PID 22227",
> [file: "slot.c", line: "516", routine: "ReplicationSlotAcquire", severity: "ERROR"]
> ```

This looks like a symptom of multiple Electric instances connecting to the same Postgres. As mentioned in the updated docs, pass the `--ha=false` to `fly deploy` to prevent Fly from spanning two machines for your Electric app.

Let me know if that helps.

**Comment by alco** [comment]
I'm closing this as an old issue that hasn't seen any activity recently.

Electric can now be configured to run in [the `direct_writes` mode](https://electric-sql.com/blog/2023/12/13/electricsql-v0.8-released#from-superuser-to-supabase) in which it doesn't work with Postgres subscription at all. The latest [v0.9 release](https://electric-sql.com/blog/2024/01/24/electricsql-v0.9-released#configuration-improvements-for-easier-deployments) introduces improvements to SSL and IPv6 handling.

Today it's easier than before to start out with Electric by going through our updated [Fly deployment guide](https://electric-sql.com/docs/deployment/fly).
