### ISSUE TITLE
No ports exposed in this image（ docker windows client）

### ISSUE THREAD

**Issue by whwnow** [electric-sql/electric#582]
I'm using the Windows client of Docker, and I can't fill in the port mapping as shown in the following picture.
![image](https://github.com/electric-sql/electric/assets/1713701/4a6c2365-4d3d-4847-81be-292448a3a862)

**Comment by kevin-dp** [comment]
Hi @whwnow

Could you provide additional details about how you ran the image.
You need to expose the necessary ports when running the image.
For instance, when creating an Electric application using the `create-electric-app` starter, we provide a docker-compose file that exposes the necessary ports:

```
npx create-electric-app@latest my-app
cat my-app/backend/compose/docker-compose.yaml
```
 
This displays:
```
  ...
  electric:
    image: "${ELECTRIC_IMAGE:-electricsql/electric:latest}"
    ...
    ports:
      - 5133:5133
    ...
```

Notice that we explicitly bind port `5133` to port `5133` on the host machine.

Or to run Electric on top of an existing Postgres database:

```
cat my-app/backend/startElectric.js
```

Prints:

```
...
shell.exec(
  `docker run \
      -e "DATABASE_URL=${db}" \
      -e "LOGICAL_PUBLISHER_HOST=localhost" \
      -e "AUTH_MODE=insecure" \
      -p 5133:5133 \
      -p 5433:5433 ${electric}`
)
```

Notice again that we expose ports `5133` and `5433`.
More information about the ports can be found in [the docs](https://electric-sql.com/docs/api/service#core-config).

**Comment by thruflo** [comment]
It may be that the Windows GUI requires explicitly exposed `PORT`s in the Dockerfile. Which eg https://github.com/electric-sql/electric/blob/main/components/electric/Dockerfile doesn’t provide.

**Comment by whwnow** [comment]
> Hi @whwnow
> 
> Could you provide additional details about how you ran the image. You need to expose the necessary ports when running the image. For instance, when creating an Electric application using the `create-electric-app` starter, we provide a docker-compose file that exposes the necessary ports:
> 
> ```
> npx create-electric-app@latest my-app
> cat my-app/backend/compose/docker-compose.yaml
> ```
> 
> This displays:
> 
> ```
>   ...
>   electric:
>     image: "${ELECTRIC_IMAGE:-electricsql/electric:latest}"
>     ...
>     ports:
>       - 5133:5133
>     ...
> ```
> 
> Notice that we explicitly bind port `5133` to port `5133` on the host machine.
> 
> Or to run Electric on top of an existing Postgres database:
> 
> ```
> cat my-app/backend/startElectric.js
> ```
> 
> Prints:
> 
> ```
> ...
> shell.exec(
>   `docker run \
>       -e "DATABASE_URL=${db}" \
>       -e "LOGICAL_PUBLISHER_HOST=localhost" \
>       -e "AUTH_MODE=insecure" \
>       -p 5133:5133 \
>       -p 5433:5433 ${electric}`
> )
> ```
> 
> Notice again that we expose ports `5133` and `5433`. More information about the ports can be found in [the docs](https://electric-sql.com/docs/api/service#core-config).

I didn't run image from commnd. Just click the "run" button on windows GUI.
![image](https://github.com/electric-sql/electric/assets/1713701/f3ba719e-025b-44ba-9f08-e552e823fd81)

**Comment by kevin-dp** [comment]
> > Hi @whwnow
> > Could you provide additional details about how you ran the image. You need to expose the necessary ports when running the image. For instance, when creating an Electric application using the `create-electric-app` starter, we provide a docker-compose file that exposes the necessary ports:
> > ```
> > npx create-electric-app@latest my-app
> > cat my-app/backend/compose/docker-compose.yaml
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This displays:
> > ```
> >   ...
> >   electric:
> >     image: "${ELECTRIC_IMAGE:-electricsql/electric:latest}"
> >     ...
> >     ports:
> >       - 5133:5133
> >     ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Notice that we explicitly bind port `5133` to port `5133` on the host machine.
> > Or to run Electric on top of an existing Postgres database:
> > ```
> > cat my-app/backend/startElectric.js
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Prints:
> > ```
> > ...
> > shell.exec(
> >   `docker run \
> >       -e "DATABASE_URL=${db}" \
> >       -e "LOGICAL_PUBLISHER_HOST=localhost" \
> >       -e "AUTH_MODE=insecure" \
> >       -p 5133:5133 \
> >       -p 5433:5433 ${electric}`
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Notice again that we expose ports `5133` and `5433`. More information about the ports can be found in [the docs](https://electric-sql.com/docs/api/service#core-config).
> 
> I didn't run image from commnd. Just click the "run" button on windows GUI. ![image](https://user-images.githubusercontent.com/1713701/277420454-f3ba719e-025b-44ba-9f08-e552e823fd81.png)

Yes that's the problem. When running the image you must provide some arguments and expose the necessary ports. As explained in my previous message, you can do that either by running the compose file or by passing those arguments using `docker run`. You can also find this in our documentation: https://electric-sql.com/docs/usage/installation/service
