### ISSUE TITLE
[VAX-1251] Catch and wrap raw SQLite errors

### ISSUE THREAD

**Issue by balegas** [electric-sql/electric#586]
In certain cases we don't catch SQLite errors and propagate them as they arrive from the database driver. 

In this task we unify raw SQLite error messages to have a common representation that developers can work with at app-level if necessary.

**Comment by KyleAMathews** [comment]
👋 we've been working the last month on a rebuild of the Electric server over at a temporary repo https://github.com/electric-sql/electric-next/

You can read more about why we made the decision at https://next.electric-sql.com/about

We're really excited about all the new possibilities the new server brings and we hope you'll check it out soon and give us your feedback.

We're now moving the temporary repo back here. As part of that migration we're closing all the old issues and PRs. We really appreciate you taking the time to investigate and report this issue!
