### ISSUE TITLE
The protocol timeout is hardcoded

### ISSUE THREAD

**Issue by gorbak25** [electric-sql/electric#605]
https://github.com/electric-sql/electric/blob/3fdb28908b08141e3ee74b4cd1dcb283fd5df70d/clients/typescript/src/satellite/config.ts#L55

When electric requests a lot of data the default timeout which is hard-coded to 3000 is sometimes not enough and I see no way to increase it.
![image](https://github.com/electric-sql/electric/assets/1352848/44a29090-3c01-4f55-a991-715fbaca4f47)
[...]
![image](https://github.com/electric-sql/electric/assets/1352848/b186b338-d962-4b22-a14c-0e2a2f4a0217)

**Comment by balegas** [comment]
We'll expose ```SatelliteClientOpts.timeout```

**Comment by kevin-dp** [comment]
This feature has been implemented in https://github.com/electric-sql/electric/pull/637 which is now merged into main. It will be part of our next patch release.
