### ISSUE TITLE
"Invalid descriptor (capacitor-community/sqlite)" when installing electric-sql@0.7.0 with yarn

### ISSUE THREAD

**Issue by michael42** [electric-sql/electric#627]
Hi,

I'm just trying out electric-sql and it seems there's an [inconsistency](https://github.com/electric-sql/electric/blob/b94a71865b7dc0aa3cf28e84c35d28360ab83e87/clients/typescript/package.json#L235) between the `peerDependencies` and `peerDependenciesMeta`:

```
  "peerDependencies": {
    "@capacitor-community/sqlite": ">= 5.4.1",
   [...]
  },
  "peerDependenciesMeta": {
    "capacitor-community/sqlite": { "optional": true },
    [...]
  },
```

`peerDependencies` references `@capacitor-community/sqlite`, while `peerDependenciesMeta` references an invalid `capacitor-community/sqlite`. I think this is why installing electric-sql fails with yarn:

```
$ yarn add electric-sql@0.7.0
➤ · Yarn 4.0.1
➤ ┌ Resolution step
➤ │ Error: electric-sql@npm:0.7.0: Invalid descriptor (capacitor-community/sqlite)
    at nh ($HOME/.cache/node/corepack/yarn/4.0.1/yarn.js:140:109587)
    at cE.load ($HOME/.cache/node/corepack/yarn/4.0.1/yarn.js:140:125463)
    at hv.resolve ($HOME/.cache/node/corepack/yarn/4.0.1/yarn.js:678:5987)
    at async Bd.resolve ($HOME/.cache/node/corepack/yarn/4.0.1/yarn.js:141:1451)
    at async Bd.resolve ($HOME/.cache/node/corepack/yarn/4.0.1/yarn.js:141:1451)
    at async $HOME/.cache/node/corepack/yarn/4.0.1/yarn.js:210:7174
    at async Yy ($HOME/.cache/node/corepack/yarn/4.0.1/yarn.js:140:53916)
    at async ne ($HOME/.cache/node/corepack/yarn/4.0.1/yarn.js:210:7156)
    at async Promise.allSettled (index 10)
    at async Uc ($HOME/.cache/node/corepack/yarn/4.0.1/yarn.js:140:53250)
➤ └ Completed
➤ · Failed with errors in 0s 97ms
```

Installing `electric-sql@0.6.4` works fine.

**Comment by ccapndave** [comment]
Same issue here

**Comment by samwillis** [comment]
Thanks for the report, I've merged a fix and it will be out in the next release.

**Comment by ccapndave** [comment]
Awesome!  Could I ask approximately when you think the next release will come out, so I know if we should wait or work around it in the meantime?

**Comment by thruflo** [comment]
We could do a quick patch release, right?

**Comment by ccapndave** [comment]
No stress - it works with `npm` so we have an easy workaround

**Comment by ccapndave** [comment]
Ah, so it turns out that it *installs* with npm, but when I actually try to use `@capacitor-community/sqlite` the error surfaces with npm too.  Would it be possible to push out a patch release?

**Comment by alco** [comment]
Hey @ccapndave. It is likely that we'll publish a patch release this week. Stay tuned.
