### ISSUE TITLE
Electric eats my data when `SET LOCAL session_replication_role = replica` is set

### ISSUE THREAD

**Issue by gorbak25** [electric-sql/electric#650]
In my quest to migrate from electric 0.6.3 to 0.7.1 I've settled on this migration plan:
1. Dump the user data from the database running electric 0.6.3
2. Create a new database with the electic 0.7.1(and changed migrations) 
3. Load the user data into the new database with electric 0.7.1

As i want to change the schema and use the new migration proxy i cant use pg_dump & pg_restore. I've wrote a script which dumps all the important data to a json and another script which restores it. In order to simplify the restore script and not care about ordering between tables I'm setting `SET LOCAL session_replication_role = replica` during the restore so i may load data in any order I want. 

It turns out that data gets restored only in non electrified tables! The electrified tables end up empty .-. When I'm using `SET LOCAL session_replication_role = origin` the  data gets indeed loaded properly into the tables(i've tested on a few electrified tables)

Why data inserted with `SET LOCAL session_replication_role = replica` get's deleted by electric?(I'm still testing on 0.6.3)

**Comment by gorbak25** [comment]
I've settled for manually disabling triggers while i'm messing with the database. Everything works. Electric properly reconciles the client state after an db restore. Here's the code if someone else wants to do something similar:
```
  await db.$transaction(async (tx: Prisma.TransactionClient) => {
    console.log("Transaction opened. Locking all tables");
    // Enable serializable isolation level
    await tx.$executeRawUnsafe("SET LOCAL TRANSACTION ISOLATION LEVEL SERIALIZABLE;");
    // Lock all tables in exclusive access mode
    await waitForPromises(
      allTables.map(async (table) => await tx.$queryRawUnsafe(`LOCK TABLE ${table} IN ACCESS EXCLUSIVE MODE`)),
    );

    console.log("Introspecting triggers");
    // First explicitly get what triggers are currently enabled
    const getTriggersFun = async (): Promise<{ triggerName: string, tableName: string, triggerMode: string }[]> => {
      return (await waitForPromises(allTables.map(async (tableName) => await tx.$queryRawUnsafe(`SELECT 
      tgname AS "triggerName", 
      '${tableName}' AS "tableName", 
      t.tgenabled AS "triggerMode"
  FROM 
      pg_trigger t
  WHERE 
      t.tgrelid = '${tableName}'::regclass::oid
      -- 'A' for ALWAYS, 'R' for REPLICA, 'O' for ORIGIN/LOCAL
      AND t.tgenabled IN ('A', 'R', 'O')
      ORDER BY "tableName", "triggerName";`)),
      ) as any).flat()
        // Ignore triggers from electric
        .filter((x: any) =>
          (x.triggerName as string).indexOf("shadow_rows") < 0
          && (x.triggerName as string).indexOf("tombstone_table") < 0
          && (x.triggerName as string).indexOf("satellite_write") < 0
        ) as any;
    };

    const triggers = await getTriggersFun();
    console.log("Disabling triggers");
    await waitForPromises(triggers.map((x) => tx.$queryRawUnsafe(`ALTER TABLE ${x.tableName} DISABLE TRIGGER "${x.triggerName}"`)));
    // Sanity check that the triggers got disabled
    if ((await getTriggersFun()).length !== 0) throw new Error("Disabling triggers failed!")
    try {
    // LOAD DATA INTO TABLES
    } finally {
      console.log("Restoring triggers")
      // Reenable the triggers
      await waitForPromises(triggers.map((x) =>
        tx.$queryRawUnsafe(`ALTER TABLE ${x.tableName} ENABLE ${x.triggerMode === "A" ? "ALWAYS" : x.triggerMode === "R" ? "REPLICA" : ""} TRIGGER "${x.triggerName}"`)));
      // Sanity check that the triggers ended up in the initial state
      const finalTriggers = await getTriggersFun();
      if (!isEqual(triggers, finalTriggers)) {
        // eslint-disable-next-line no-unsafe-finally
        throw new Error(`Restoring triggers failed!, ${humanReadableObjectDiff(triggers, finalTriggers)}`)
      }
    }
    console.log("Commiting transaction");
  });
```

**Comment by balegas** [comment]
To give a bit of context, there are different triggers for when an operation is coming from the replication stream, or executed by a Pg client directly. It makes sense that when enabling the replica mode for migrating data, you need to disable the triggers associated with replica mode
