### ISSUE TITLE
client:generate: Unsupported flag '--proxy' passed to generate command

### ISSUE THREAD

**Issue by barbalex** [electric-sql/electric#654]
I have previously tried to follow the [quickstart](https://electric-sql.com/docs/quickstart) on Windows (my PC).
Which did not work due to the process not being tested there.

I then managed to run it successfully on MacOS (my Notebook).

Because I do not want to work on a big new project only on my notebook, I have now created a dual boot with Pop OS linux.

Following the quickstart on Pop OS gives me this error:
```
alex@pop-os:~/ps$ yarn client:generate
yarn run v1.22.19
warning package.json: No license field
$ yarn electric:check && npx electric-sql generate --service http://localhost:5133 --proxy postgresql://prisma:proxy_password@localhost:65432/electric
warning package.json: No license field
$ node ./check-electric-is-running.js
Unsupported flag '--proxy' passed to generate command.
error Command failed with exit code 9.
```

More info:
- electric-sql: 0.7.1
- @electric-sql/prisma-generator: 1.1.0
- node 20.9.0 (this is different than on my MacOS notebook where it is 19.3.0)

**Comment by barbalex** [comment]
This is rather weird. I now used npm instead of yarn:
```
npm i
npm run client:generate
```
...and it works :shrug:

**Comment by thruflo** [comment]
Maybe npm did a fresh install and that got the latest electric-sql which supports the proxy?

**Comment by barbalex** [comment]
> Maybe npm did a fresh install and that got the latest electric-sql which supports the proxy?

I don't think so. It was the first install on Pop OS and I installed Yarn just before (don't use it any more in other projects).

Anyway, closing - seems a bit unusual.
