### ISSUE TITLE
Prepared statements in wa-sqlite are not cached

### ISSUE THREAD

**Issue by gorbak25** [electric-sql/electric#681]
https://github.com/electric-sql/electric/blob/d385d3cf7eb4c8822afefdd6173fad7feb71712a/clients/typescript/src/drivers/wa-sqlite/database.ts#L45

`prepare_v2` generates a new query plan every time it's called. Consider keeping a cache of prepared statements.

**Comment by samwillis** [comment]
Amusingly I've been looking a little into this this afternoon. 🤣

Compiled prepared statements include a query plan, and so we probably want to clear any cache whenever migrations are applied.

**Comment by gorbak25** [comment]
@samwillis sqlite invalidates the query plan in prepared statements when the schema changes. The query plan will be regenerated when you will try to execute a query(calling sqlite_step). No special handling is required.
