### ISSUE TITLE
critical section for wa-sqlite isn't properly scoped

### ISSUE THREAD

**Issue by rhashimoto** [electric-sql/electric#682]
I don't think the synchronization in this method is correct:

https://github.com/electric-sql/electric/blob/d385d3cf7eb4c8822afefdd6173fad7feb71712a/clients/typescript/src/drivers/wa-sqlite/database.ts#L37-L87

The mutex should protect _all_ the wa-sqlite calls but it is unconditionally released at [line 50](https://github.com/electric-sql/electric/blob/d385d3cf7eb4c8822afefdd6173fad7feb71712a/clients/typescript/src/drivers/wa-sqlite/database.ts#L50).

**Comment by kevin-dp** [comment]
Indeed, the mutex should not be released on line 50.
Additionally, we should wrap everything from line 42 onward in a single try..finally block to ensure that the mutex is correctly released. I will fix this. Thanks for reporting this and for your awesome work on wa-sqlite :-)

**Comment by rhashimoto** [comment]
Sounds good! Off-topic, there was a [critical bug fixed in IDBBatchAtomicVFS](https://github.com/rhashimoto/wa-sqlite/discussions/120) recently. I'm not sure if or how you track wa-sqlite changes, just wanted to be sure you folks were aware.
