### ISSUE TITLE
Weird documentation doing a React Native install

### ISSUE THREAD

**Issue by lawik** [electric-sql/electric#733]
Trying to get a React Native project up and running with Electric I have hit problems where I hit unmet dependencies trying to `npx` the generation script because you will likely be missing the electric libraries. Seems like `yarn`:ing it works fine. Some notes covering that process inside the React Native docs would be good to avoid wild confusion and mixed tooling.

**Comment by msfstef** [comment]
@lawik is this still an issue? The documentation and example have been updated for React Native, as well as the driver used ([see doc page](https://electric-sql.com/docs/integrations/drivers/mobile/react-native)) and a [CLI](https://electric-sql.com/docs/api/cli) has been introduced to facilitate the setup and generation steps.

**Comment by lawik** [comment]
I won't be trying it, sounds likely that it would work better with that updated.
