### ISSUE TITLE
PG_PROXY_URL not honored. Should be replaced with ELECTRIC_PROXY_URL

### ISSUE THREAD

**Issue by jljorgenson18** [electric-sql/electric#740]
It looks like PG_PROXY_URL is not used at all. It looks like internally electric is actually expecting `ELECTRIC_PROXY_URL` 

Were the docs just not updated or should it be set to Electric Proxy URL?

<img width="981" alt="Captura de Tela 2023-12-08 às 5 31 08 PM" src="https://github.com/electric-sql/electric/assets/5751354/adc39f02-9531-43aa-9b44-076d9f2e6325">

**Comment by samwillis** [comment]
Hey, @jljorgenson18 

Thanks for the report. Yes, this is a documentation error, the correct env var is `ELECTRIC_PROXY_URL`

**Comment by alco** [comment]
Fixed in https://github.com/electric-sql/electric/pull/747.
