### ISSUE TITLE
Prisma generator script not working in monorepos

### ISSUE THREAD

**Issue by jljorgenson18** [electric-sql/electric#741]
If you are using a monorepo, a node_module path  is generated based on the current project location

```
generator electric {
  provider      = "/home/projects/root-project/apps/some_project/node_modules/@electric-sql/prisma-generator/dist/bin.js"
  output        = "/home/projects/root-project/apps/some_project/src/generated/client"
  relationModel = "false"
}
```

Even though the module is inside of `/home/projects/root-project/node_module`

yarn has a "nohoist" option but npm workspaces does not. Ideally there would be an attempt to resolve the package first with require.resolve before generating the package path.

**Comment by samwillis** [comment]
Hey @jljorgenson18 

Thanks for the report. I think this PR (#645) I'm aiming to merge on Monday should fix it as it changes the way we resolve the path to the Prisma generator. I will test in a monorepo 😄
