### ISSUE TITLE
Unable to pull docker image in supabase example

### ISSUE THREAD

**Issue by sambarrowclough** [electric-sql/electric#752]
I'm trying to get the branch of electric with the basic supabase demo working, but having no luck.

I spotted you have docs on getting started with supabase so thought i'd have a crack.

the repo: git clone -b samwillis/basic-supabase-demo https://github.com/electric-sql/electric.git

the error message when running npm run backend:up: 
Error response from daemon: pull access denied for electric, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

changing line 416 in /examples/supabase-basic/backend/docker-compose.yml fixes the issue:

`image: "${ELECTRIC_IMAGE:-electricsql/electric:latest}"` ->   `image: "electricsql/electric:canary"`

**Comment by alco** [comment]
Hey @sambarrowclough. That version of the example in that branch is still WIP. We'll make sure to update the relevant image reference once we publish an official release that makes connecting to Supabase possible. Stay tuned!

**Comment by samwillis** [comment]
Hey @sambarrowclough,

Good spot! I'm just putting the finishing touches to the demo. We are releasing a new version this week with all the bits in place so you won't have to use the "canary" tagged image.
