### ISSUE TITLE
Electric mesh allows connection only in `replication=database` mode

### ISSUE THREAD

**Issue by JCKodel** [electric-sql/electric#778]
While using a newly installed postgres 16 (running on bare metal).

How to fix it?

**Comment by alco** [comment]
Hey @JCKodel. If you're running the latest version of Electric, set the configuration option `ELECTRIC_WRITE_TO_PG_MODE` to `direct_writes` and restart Electric. You may still see error messages about subscriptions in Electric logs. You can get rid of those by manually delete the subscription that was created by Electric when it connected to the database for the first time as described in https://github.com/electric-sql/electric/issues/569#issuecomment-1779339695.
