### ISSUE TITLE
Feature request: Dart support

### ISSUE THREAD

**Issue by JCKodel** [electric-sql/electric#781]
Flutter has surpass React Native popularity since at least Jan 2021, isn't time to think about real mobile apps instead of websites?

![image](https://github.com/electric-sql/electric/assets/379339/948e26fe-fc50-45f7-9572-92894c017138)

https://www.powersync.com/ has a very nice Dart API, but it is a cloud-only service :(

**Comment by davidmartos96** [comment]
@JCKodel There is https://github.com/SkillDevs/electric_dart which is an unofficial port of the client, up to date with latest version of the Official client, and with integration with the drift package for a typed database access

**Comment by kevin-dp** [comment]
I'm closing this issue as @davidmartos96 pointed out there is a Dart client for Electric.

**Comment by zifeo** [comment]
@kevin-dp can this be reopen following the rewrite?

**Comment by kevin-dp** [comment]
@zifeo I invite you to open a new issue for this to avoid any confusion.
