### ISSUE TITLE
Import Extension Issues in Electric Client Generation

### ISSUE THREAD

**Issue by SamuelCivalgo** [electric-sql/electric#798]
When creating the electric client at the top of the index.ts file import, it defaults to importing a .js file, but it generated .ts files, causing the code to malfunction. My workaround is to simply omit the extension, which then correctly locates the corresponding file. I believe the generator should remove the file extension in the client import to resolve this issue.

Problem:

![image](https://uploads.linear.app/0467b297-8a55-4fc0-82da-624730a09e44/1553925d-8d12-47c0-bd4b-b5c590e0503f/b6ad8e33-fdcc-4b38-89c9-ddd2d2daee4d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzA0NjdiMjk3LThhNTUtNGZjMC04MmRhLTYyNDczMGEwOWU0NC8xNTUzOTI1ZC04ZDEyLTQ3YzAtYmQ0Yi1iNWM1OTBlMDUwM2YvYjZhZDhlMzMtZmRjYy00YjM4LTg5YzktZGRkMmQyZGFlZTRkIiwiaWF0IjoxNzA0Mzk5MTk1LCJleHAiOjMzMjc0OTU5MTk1fQ.0tkw4P7bDLPR1Q71-ev1yFwWe6iaf7jvUrcLLvI9xSg)

![image](https://uploads.linear.app/0467b297-8a55-4fc0-82da-624730a09e44/2382508f-c7e8-444a-a34a-2756fccdde5e/7e42a011-9e8c-4191-acb9-8d04b34b2ebf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzA0NjdiMjk3LThhNTUtNGZjMC04MmRhLTYyNDczMGEwOWU0NC8yMzgyNTA4Zi1jN2U4LTQ0NGEtYTM0YS0yNzU2ZmNjZGRlNWUvN2U0MmEwMTEtOWU4Yy00MTkxLWFjYjktOGQwNGIzNGIyZWJmIiwiaWF0IjoxNzA0Mzk5MTk1LCJleHAiOjMzMjc0OTU5MTk1fQ.dkYBsEi2QLF4HwSFiVnQetB-nVI3agOsO36MM4Dac_Y)

Solution:

![image](https://uploads.linear.app/0467b297-8a55-4fc0-82da-624730a09e44/b351d55a-8b55-494a-b7a5-0598b74aeadd/01328578-c311-462c-955e-b88da430a658?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzA0NjdiMjk3LThhNTUtNGZjMC04MmRhLTYyNDczMGEwOWU0NC9iMzUxZDU1YS04YjU1LTQ5NGEtYjdhNS0wNTk4Yjc0YWVhZGQvMDEzMjg1NzgtYzMxMS00NjJjLTk1NWUtYjg4ZGE0MzBhNjU4IiwiaWF0IjoxNzA0Mzk5MTk1LCJleHAiOjMzMjc0OTU5MTk1fQ.s3GfHffD6iIcXSoGSaIc2-jejDHBPWHib4vL7giStmM)

**Comment by samwillis** [comment]
Hey @SamuelCivalgo 

Thanks for the report. There are some complexities with Typescript and import file extensions. The new(ish) tsconfig `"moduleResolution": "nodenext"` option requires all imports to use the .js extension, even if they are a .ts or .tsx extension, and this is the intended design going forward.

I was under the impression this was fully backwards compatible and we could just add the .js to make our client compatible with all configurations, however it seems there is a problem.

Could you paste your tsconfig.json? I'm trying to understand which configurations require which extensions.

It's looking like we will need to inspect the projects tsconfig to determine the style of imports required.

**Comment by SamuelCivalgo** [comment]
Here's my tsconfig.json:

```
{
  "compilerOptions": {
    "jsx": "react",
    "module": "ESNext",
    "experimentalDecorators": true,
    "noUncheckedIndexedAccess": true,
    "strict": true
  },
  "exclude": ["app.config.ts"],
  "extends": "expo/tsconfig.base"
}
```

**Comment by SamuelCivalgo** [comment]
if you want to know the content of the expo/tsconfig.base from expo this is it: 

```
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Expo",

  "compilerOptions": {
    "allowJs": true,
    "esModuleInterop": true,
    "jsx": "react-native",
    "lib": ["DOM", "ESNext"],
    "moduleResolution": "node",
    "noEmit": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "target": "ESNext"
  },

  "exclude": ["node_modules", "babel.config.js", "metro.config.js", "jest.config.js"]
}
```

**Comment by samwillis** [comment]
Hey,

Quick update on this, I got to the bottom of it, essentially there is no way to generate import statements that are compatible with all tsconfig configurations *and* all bundler configurations.

We have reverted the change to the generator #821, and are implementing an additional argument to the generate command to specify `--module-resolution=nodenext` when required. This will drop in the new CLI (#664) in the next version.

**Comment by nurturenature** [comment]
Confirming using 0.9.0 and:
```json
{
  "scripts": {
    "prebuild": "npx electric-sql generate --module-resolution nodenext"
  }
}

{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ES2022",
    "moduleResolution": "Bundler"
  }
}
```
works.

`--module-resolution nodenext` was required.

**Comment by msfstef** [comment]
Is this still an issue or has it been resolved with the new CLI flag?
