### ISSUE TITLE
typescript clientside: Is there a way to turn off the websocket temporarily?

### ISSUE THREAD

**Issue by archywillhe** [electric-sql/electric#822]
I noticed we can't really set the url `null`

```
const config = {
        auth: {
          token: authToken(),
        },
        url: "ws://localhost:8080",
      };
```

Is there a way to turn off `electric` websocket and use this library solely locally ? Thanks!

i.e. so it will stop pinging the websocket endpoint

```
web.js:1 WebSocket connection to 'ws://localhost:8080/ws' failed
```

**Comment by archywillhe** [comment]
I'm digging into the code; looks like something to do with Satellite ? so we can just do `satellite.stop()` ?

(Basically I want to be able run my app 100% locally first - and worry about the Postgres syncing later on)

**Comment by archywillhe** [comment]
(I tried turning off `satellite` and the db operation stopped working all together.) So basically my use case is just to have the SQLite locally and be able to turn the sync on or off.

**Comment by msfstef** [comment]
The React client has a hook called `useConnectivityState` , which exposes the status of the satellite connection and also a `toggleConnectivityState` method you can use to disable/enable the syncing and emulate being offline w.r.t. to the sync service.

This API is likely to change, with the connectivity state being read-only and the ability to toggle moved elsewhere, but for the time being I think this should do what you're asking (?)

**Comment by thruflo** [comment]
One short term thing in development is just to ignore the satellite websocket polling errors for now.

As @msfstef says, we will have an ergonomic API for running in local-only mode and we're also about to release an update to the CLI that supports building the type safe client without running the backend services (as per https://github.com/electric-sql/electric/pull/820#discussion_r1447714998).

**Comment by archywillhe** [comment]
awww this is so cool! lovely! thanks!

looking forward!
