### ISSUE TITLE
Truncation not supported?

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#858]
I truncated a table in my database and Electric has refused to start working again failing over and over with this error upon connecting to the db:

```
** (CaseClauseError) no case clause matching: Electric.Replication.Changes.TruncatedRelation
    (electric 0.8.1) lib/electric/replication/changes.ex:64: anonymous fn/2 in Electric
.Replication.Changes.Transaction.count_operations/1
    (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (electric 0.8.1) lib/electric/replication/postgres/logical_replication_producer.ex:
260: Electric.Replication.Postgres.LogicalReplicationProducer.process_message/2
    (gen_stage 1.2.1) lib/gen_stage.ex:2206: GenStage.noreply_callback/3
    (stdlib 4.3.1.2) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3.1.2) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:epgsql, #PID<0.7622.0>, {:x_log_data, 104772744, 104772744, <<67, 0, 0,
 0, 0, 0, 6, 62, 179, 24, 0, 0, 0, 0, 6, 62, 180, 136, 0, 2, 178, 65, 114, 177, 227, 18
0>>}}
02:16:49.407 pid=<0.7308.0> pg_producer=postgres_1 [warning] producer is down: {:via, :
gproc, {:n, :l, {Electric.Replication.Postgres.LogicalReplicationProducer, "postgres_1"
}}}
02:16:49.410 pid=<0.7308.0> pg_producer=postgres_1 [warning] producer is down: {:via, :
gproc, {:n, :l, {Electric.Replication.Postgres.LogicalReplicationProducer, "postgres_1"
}}}
 
```

**Comment by KyleAMathews** [comment]
There doesn't seem to be any way to fix this as I assume what's happening is it connects to Postgres, sees the truncation and than drops the connection only to try again in a few seconds. This is very early in a project so I'll just drop the prod database and restart.

**Comment by samwillis** [comment]
Hey @KyleAMathews,

Yes, 'TRUNCATE' isn't currently supported. There are a few issues we need to solve around 'on delete' triggers that don't get fired correctly with a truncate, and so compensations wouldn't work.

For now I would recommend 'DELETE FROM table_name;'

We need to add this to the documentation.

**Comment by alco** [comment]
We could create `ON TRUNCATE` triggers for electrified tables what would raise and abort the attempt to truncate. Just an idea of a safe-guard in addition to documenting this limitation on the website.

**Comment by thruflo** [comment]
That would be awesome. I didn’t know there were on truncate triggers.

Out of interest, could we not write a “this table was truncated” record and pass it through the protocol?

**Comment by alco** [comment]
> Out of interest, could we not write a “this table was truncated” record and pass it through the protocol?

We could, in principle.

**Comment by balegas** [comment]
Just to raise that ON TRUNCATE trigger does not seem to be available in SQLITE

**Comment by thruflo** [comment]
That explains it 🤣 

I do think support for PG truncate would be v valuable. Because it's a common sysadmin action. No one iterates through a large table when they don't have to.

I think in the client, we arguable control more of the data access layer (so our deleteMany does not use a truncate) and it's fine to document that truncates are not allowed.
