### ISSUE TITLE
New dependency for electric-sql "dotenv-flow" is warning if site has no .env files

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#870]
`[dotenv-flow@4.1.0]: ".env*" files loading failed: no ".env*" files matching pattern ".env[.node_env][.local]" in "/Users/kylemathews/programs/garmin-data" dir undefined`

This doesn't seem to be blocking anything but is spurious.

**Comment by samwillis** [comment]
Hey, yes it's unfortunate that dotenv-flow throws that warning when there is no `.env` files. When I looked into it there didn't seem to be a way to silence the warning. I will look into it again and see if there is an alternative to dotenv-flow.
