### ISSUE TITLE
The electric-sql generate --proxy flag is broken in electric-sql@0.9

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#871]
It just creates a url from the other possible env variables resulting in something like: `Proxy URL: postgresql://prisma:proxy_password@localhost:65432/garmin-app`

**Comment by KyleAMathews** [comment]
actually, this means it doesn't work anywhere. I was testing locally and it seemed like it was working but then I realized it was because it was connecting to a local running electric process.

**Comment by samwillis** [comment]
Hey @KyleAMathews 

Thanks for the report, yes there's a bug in the generate command. `--proxy` should be overriding the env vars and defaults but isn't. I will have a PR fixing this ready today.

Until then you can use `--pg-proxy-host`, `--pg-proxy-port` etc to override individual parts. To see the full list run `npx electric-sql help generate`.

**Comment by KyleAMathews** [comment]
Thanks!
