### ISSUE TITLE
missing StringFieldRefInputSchema in generated client

### ISSUE THREAD

**Issue by ImSingee** [electric-sql/electric#881]
After upgrade electric-sql (from 0.8.2) to v0.9.1, I can't build my project any more.

<img width="849" alt="image" src="https://github.com/electric-sql/electric/assets/11208082/29805fb5-3e0b-43f8-a96c-406bc48764b5">

I tried to upgrade `prisma` and `@prisma/client` to 5.2.0 (previous 4.8.1) but it not works.

**Comment by ccapndave** [comment]
I've got the same problem with these types:

- `StringFieldRefInputSchema`
- `ListStringFieldRefInputSchema`
- `FloatFieldRefInputSchema`
- `DateTimeFieldRefInputSchema`
- `IntFieldRefInputSchema`
- `ListIntFieldRefInputSchema`
