### ISSUE TITLE
Allow updating auth token when trying to reconnect

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#892]
![Screen Shot 2024-01-25 at 8 40 29 AM](https://uploads.linear.app/0467b297-8a55-4fc0-82da-624730a09e44/a617583f-4532-40bb-a126-d99bf8c9d51d/5bb6180d-3328-447b-be1d-5278f02a5eea?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzA0NjdiMjk3LThhNTUtNGZjMC04MmRhLTYyNDczMGEwOWU0NC9hNjE3NTgzZi00NTMyLTQwYmItYTEyNi1kOTliZjhjOWQ1MWQvNWJiNjE4MGQtMzMyOC00NDdiLWJlMWQtNTI3OGYwMmE1ZWVhIiwiaWF0IjoxNzA2NTM1Mzk3LCJleHAiOjMzMjc3MDk1Mzk3fQ.fPGrgQAXDCpK6inGNl7150mWuDl89veWQuW3udGNHl8 "=1191x")

This is very noticeable on mobile web as my browser closes websocket connections whenever you navigate away from the tab. But can be reproduced on desktop as well by turning off your internet and then reconnecting.

What happens is electric is setup with an auth token that has an expiration date in the near future (e.g. clerk.dev has a 60 second expiration time) so then whenever there's a reconnection attempt, it fails as the old token is now expired.

What I suggest is the config token key can take either a string or an async function — so when reconnecting, the app's code can get a fresh token on demand e.g.

```
async function getToken () {
  // Call external API
}
 
const config = {
  auth: {
    token: getToken,
  }
}
initElectric(config)
```

**Comment by kevin-dp** [comment]
Hi @KyleAMathews,
I have an open PR #791 that introduces `connect` and `renew` methods on the Electric client.
`connect` can be used to connect to Electric, e.g. when the token expired. So you can pass a new token to connect (as long as the "sub" claim remains the same). And `renew` can be used to renew the token before it expires such that you don't experience a disconnection. An example usage (code not tested) is provided here: https://github.com/electric-sql/electric/pull/791#issuecomment-1898211939

Would that suit your needs?

**Comment by KyleAMathews** [comment]
Ah nice!

It does seem simpler to have electric call out to our code instead of vice versa since electric doesn't disconnect someone when a token expires right? Or will that change as well? Calling renew on a loop would work fine though.

**Comment by KyleAMathews** [comment]
Ah read the whole or and you are going to log people out. Yeah I like the renew API then 👍

**Comment by KyleAMathews** [comment]
yup!

**Comment by KyleAMathews** [comment]
Hmm actually the docs are missing what the suggested flow for catching JWT expiration errors and reconnecting is — I think I can sort it out from the PR but it'd be nice to have the suggested code there.

**Comment by KyleAMathews** [comment]
This is what I ended up doing https://github.com/KyleAMathews/electric-query/commit/8721875d14c40797018e668886f9b1c68b6bf39d
