### ISSUE TITLE
Reject electrification of tables outside of the public schema

### ISSUE THREAD

**Issue by balegas** [electric-sql/electric#894]
Electrification should fail for tables that are not on `public` schema.

This is a documented limitation (https://electric-sql.com/docs/usage/data-modelling/migrations#default-schema), but Electric should prevent this.

We intend to lift this restriction as part of the roadmap.
Issue was first raised in [Discord](https://discord.com/channels/933657521581858818/1174469489434316890).

**Comment by AntonOfTheWoods** [comment]
> We intend to lift this restriction as part of the roadmap.

@balegas or @alco is there somewhere we can see where this is on the roadmap? Could these "we'll do that later" be created as tickets so we can subscribe to them?
