### ISSUE TITLE
JWT token: unsigned tokens are invalid

### ISSUE THREAD

**Issue by prepor** [electric-sql/electric#900]
Hi

Documentation [suggests](https://electric-sql.com/docs/usage/auth/insecure) to use https://token.dev/ service to manually generate unsigned tokens. token.dev generates tokens like `eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJzdWIiOiIxIn0`. Note that there is only one `.`. It's totally valid unsigned JWT token. But Joken library doesn't support them at all (see the line
https://github.com/joken-elixir/joken/blob/main/lib/joken.ex#L177)

I think it would be great at least to explicitly mention it in documentation and/or make more helpful error messages (right now it's `Client authentication failed: Invalid token`)

Workaround: adding `.` to the end of token helps.

**Comment by alco** [comment]
@prepor Thanks for reporting this!
