### ISSUE TITLE
flaky client generation

### ISSUE THREAD

**Issue by barbalex** [electric-sql/electric#917]
This is a typical client generation for me:
```console
PS C:\Users\alexa\ps> npm run client:generate

> ps@0.1.0 client:generate
> npx electric-sql generate && node renameLables.js

Generating Electric client...
Service URL: http://localhost:5133
Proxy URL: postgresql://prisma:********@localhost:65432/ps
generate command failed: Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\alexa\ps\src\generated\client\runtime'
PS C:\Users\alexa\ps> npm run client:generate

> ps@0.1.0 client:generate
> npx electric-sql generate && node renameLables.js

Generating Electric client...
Service URL: http://localhost:5133
Proxy URL: postgresql://prisma:********@localhost:65432/ps
generate command failed: Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\alexa\ps\src\generated\client\runtime'
PS C:\Users\alexa\ps> npm run client:generate

> ps@0.1.0 client:generate
> npx electric-sql generate && node renameLables.js

Generating Electric client...
Service URL: http://localhost:5133
Proxy URL: postgresql://prisma:********@localhost:65432/ps
generate command failed: Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\alexa\ps\src\generated\client\runtime'
PS C:\Users\alexa\ps> npm run client:generate

> ps@0.1.0 client:generate
> npx electric-sql generate && node renameLables.js

Generating Electric client...
Service URL: http://localhost:5133
Proxy URL: postgresql://prisma:********@localhost:65432/ps
generate command failed: Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\alexa\ps\src\generated\client\runtime'
PS C:\Users\alexa\ps> npm run client:generate

> ps@0.1.0 client:generate
> npx electric-sql generate && node renameLables.js

Generating Electric client...
Service URL: http://localhost:5133
Proxy URL: postgresql://prisma:********@localhost:65432/ps
generate command failed: Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\alexa\ps\src\generated\client\runtime'
PS C:\Users\alexa\ps> npm run client:generate

> ps@0.1.0 client:generate
> npx electric-sql generate && node renameLables.js

Generating Electric client...
Service URL: http://localhost:5133
Proxy URL: postgresql://prisma:********@localhost:65432/ps
Successfully generated Electric client at: ./src\generated\client
Building migrations...
Successfully built migrations
```

I work on Windows 11.

It usually works sooner or later. Often on the second or third try.

**Comment by kevin-dp** [comment]
Hi @barbalex, could you run client generation in debug mode `npx electric-sql generate --debug`.
When it fails in debug mode, you should see a temporary folder. Inside there should be a `prisma` directory with a `schema.prisma` file. From the temporary folder, could you try running `npx prisma generate` and report back here?
If this works, the issue is somewhere else in our generation process. If it fails, the problem is probably in Prisma.

**Comment by barbalex** [comment]
So I did this four times:
- `npm run backend:down`
  [+] Running 4/4
  ✔ Network ps_default       Created                                                                                                                                                                                                                         0.0s 
  ✔ Volume "ps_pg_data"      Created                                                                                                                                                                                                                         0.0s 
  ✔ Container ps-postgres-1  Created                                                                                                                                                                                                                         0.0s 
  ✔ Container ps-electric-1  Created                                                                                                                                                                                                                         0.0s 
  Attaching to electric-1, postgres-1
- `npm run backend:start`
   subscription started for postgres_1
- `npm run db:migrate`
   49 migrations applied
- `npm run client:generate`

On time it worked. Three times I got:
```
PS C:\Users\alexa\ps> npm run client:generate

> ps@0.1.0 client:generate
> npx electric-sql generate --debug

Generating Electric client...
Service URL: http://localhost:5133
Proxy URL: postgresql://prisma:********@localhost:65432/ps
generate command failed: Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\alexa\ps\src\generated\client\runtime'
```

So I found the prisma folder inside the tmp folder (I deleted the previous ones before running the commands). And ran `npx prisma generate` inside:
``````console
  PS C:\Users\alexa\ps\.electric_migrations_tmp_sXE9tM\prisma> npx prisma generate
  Environment variables loaded from ..\..\.env
  Prisma schema loaded from schema.prisma
  
  ✔ Generated Zod Prisma Types to .\..\..\src\generated\client in 811ms
  
  ✔ Generated Prisma Client (v5.2.0) to .\..\..\src\generated\client in 315ms
  Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
  ```
  import { PrismaClient } from '../../src/generated/client'
  const prisma = new PrismaClient()
  ```
  or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
  ```
  import { PrismaClient } from '../../src/generated/client/edge'
  const prisma = new PrismaClient()
  ```
  
  See other ways of importing Prisma Client: http://pris.ly/d/importing-client
  
  🛑 Hardcoding URLs in your schema poses a security risk: https://pris.ly/d/datasource-env
``````

So this seems to work?

**Comment by kevin-dp** [comment]
Indeed, that confirms the problem is with us.
After generating the Prisma and Electric clients, we remove all files and folders that we don't need. This is done here: https://github.com/electric-sql/electric/blob/main/clients/typescript/src/cli/migrations/migrate.ts#L700

It seems that Windows complains if the directory we're trying to delete is non-empty. Could you try to change that line to: `return fs.rm(filePath, { recursive: true, force: true })` in `node_modules/electric-sql/dist/cli/migrations/migrate.js` and then try running it again to see if that fixes it. Perhaps also put a `console.log` before and after that line, just to get a confirmation that it is that line that is causing the error. So:
```
console.log("Before rm");
const res = fs.rm(filePath, { recursive: true });
console.log("After rm");
return res;
```

**Comment by barbalex** [comment]
So I did:

1. alter https://github.com/barbalex/ps/blob/main/node_modules/electric-sql/dist/cli/migrations/migrate.js:
```js
async function keepOnlyPrismaTypings(prismaDir) {
  const contents = await fs.readdir(prismaDir);
  const proms = contents.map(async (fileOrDir) => {
    const filePath = path.join(prismaDir, fileOrDir);
    if (fileOrDir === "index.d.ts") {
      return fs.rename(filePath, path.join(prismaDir, "prismaClient.d.ts"));
    } else if (fileOrDir !== "index.ts") {
      // return fs.rm(filePath, { recursive: true });
      console.log("Before rm");
      const res = fs.rm(filePath, { recursive: true, force: true });
      console.log("After rm");
      return res;
    }
  });
  await Promise.all(proms);
}
```

then re-create the project four times, by running:
```console
npm run backend:down
npm run backend:start
npm run db:migrate
npm run client:generate:debug
``` 

I have altered the client generation to enable creating generated labels client side. To prevent that alteration from influencing this issue I created a separate command not doing this that I call instead to test this issue:
```json

  "scripts": {
    "client:generate:debug": "npx electric-sql generate --debug",
    "client:generate": "npx electric-sql generate && node renameLables.js"
  },
```

The result is:
```console
PS C:\Users\alexa\ps> npm run client:generate:debug

> ps@0.1.0 client:generate:debug
> npx electric-sql generate --debug

Generating Electric client...
Service URL: http://localhost:5133
Proxy URL: postgresql://prisma:********@localhost:65432/ps
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Successfully generated Electric client at: ./src\generated\client
Building migrations...
Successfully built migrations

PS C:\Users\alexa\ps> npm run client:generate:debug

> ps@0.1.0 client:generate:debug
> npx electric-sql generate --debug

Generating Electric client...
Service URL: http://localhost:5133
Proxy URL: postgresql://prisma:********@localhost:65432/ps
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
generate command failed: Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\alexa\ps\src\generated\client\runtime'

PS C:\Users\alexa\ps> npm run client:generate:debug

> ps@0.1.0 client:generate:debug
> npx electric-sql generate --debug

Generating Electric client...
Service URL: http://localhost:5133
Proxy URL: postgresql://prisma:********@localhost:65432/ps
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Successfully generated Electric client at: ./src\generated\client
Building migrations...
Successfully built migrations

PS C:\Users\alexa\ps> npm run client:generate:debug

> ps@0.1.0 client:generate:debug
> npx electric-sql generate --debug

Generating Electric client...
Service URL: http://localhost:5133
Proxy URL: postgresql://prisma:********@localhost:65432/ps
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Successfully generated Electric client at: ./src\generated\client
Building migrations...
Successfully built migrations

PS C:\Users\alexa\ps> npm run client:generate:debug

> ps@0.1.0 client:generate:debug
> npx electric-sql generate --debug

Generating Electric client...
Service URL: http://localhost:5133
Proxy URL: postgresql://prisma:********@localhost:65432/ps
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
Before rm
After rm
generate command failed: Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\alexa\ps\src\generated\client\runtime'
```

So unfortunaltely that does not seem to have helped.

**Comment by barbalex** [comment]
this has barely happened any more, maybe once in the last week
and nobody else seems to have this problem
so closing

**Comment by barbalex** [comment]
Today on my windows machine I can't generate the client at all.

I had to resort to generating it on my MacBook.

**Comment by barbalex** [comment]
This issue persists on my windows pc. I am forced to create the client on my MacOS notebook and sync it to the pc.

**Comment by kevin-dp** [comment]
Hi @barbalex, what's the issue that is preventing you from generating the client? Is it still the same "directory not empty" error?

**Comment by barbalex** [comment]
Yes. After about two weeks during which I was forced to create the client on MacOS and sync it to the pc, my pc has now reverted to the behavior in which the client generation SOMETIMES works. So I often have to generate several times, sometimes I need to restart the pc for client generation to finally work. But id _does_ work sporadically.

**Comment by barbalex** [comment]
This issue is four months old. And no one has chimed in, having the same issue. So either few devs are using windows or something is unusual in my setup. Maybe not worth putting in a lot of effort...

**Comment by kevin-dp** [comment]
Yes this is very odd.. Let's see if this happens to others too or not in which case we can take some actions.
