### ISSUE TITLE
When User: 2 offline edit the state.Then online edit the state.It cannot be edited.Some error occurred in the console

### ISSUE THREAD

**Issue by xiaobaxiang** [electric-sql/electric#924]
When User: 2 offline edit the state.Then online edit the state.Some error occurred
[https://electric-sql.com/docs/intro/offline#merging-offline-writes](https://electric-sql.com/docs/intro/offline#merging-offline-writes)
output in the console

```
Uncaught (in promise) Error: already performing snapshot
    at Pt._performSnapshot (5032.f7887850.js:2:310425)
    at Pt.mutexSnapshot (5032.f7887850.js:2:300604)
    at async f (5032.f7887850.js:2:315602)
    at async Pt._applyTransaction (5032.f7887850.js:2:316597)
    at async te.<anonymous> (5032.f7887850.js:2:333444)
```

**Comment by msfstef** [comment]
Are you able to reproduce this consistently on the website? If so, could you share with what OS, browser, and verison?

**Comment by msfstef** [comment]
Closing as stale, and website demos have now been updated to a more recent version. If the issue persists it can be reopened or opened as a new one.
