### ISSUE TITLE
Shape sync has unrecognized key "where"

### ISSUE THREAD

**Issue by andrezimpel** [electric-sql/electric#932]
I am trying to sync a shape based on the id of a record. In the docs I can find this example:
```js
await db.projects.sync({
  where: {
    id: 'abcd'
  }
})
```

Here is what I am doing:
```js
const shape = await db.organizations.sync({
  where: {
    id: "id"
  }
})
```

On my web app I then encounter this error:
```
Unhandled Runtime Error
ZodError: [
  {
    "code": "unrecognized_keys",
    "keys": [
      "where"
    ],
    "path": [],
    "message": "Unrecognized key(s) in object: 'where'"
  }
]
```

This is my organizations table:
```sql
CREATE TABLE organizations (
  id uuid NOT NULL PRIMARY KEY,
  name text NOT NULL,
  avatar_url text,

  owner_id uuid NOT NULL REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,

  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);
```

I am not quite sure what I'm doing wrong here. Also in the editor include shows up, where is not an option.

**Comment by kevin-dp** [comment]
Hi @andrezimpel,

Current support for shapes is whole-table sync only.
So you can't currently filter the rows of a table using a `where` clause.
We're working on extending shapes with where clauses, should be coming soon.
