### ISSUE TITLE
Duplicate table error when Ecto migration creates table called "roles"

### ISSUE THREAD

**Issue by justindotpub** [electric-sql/electric#959]
I have an Ecto migration that creates a table named `roles`.

```elixir
  def change do
    create table(:roles) do
      add(:name, :string)

      timestamps()
    end
  end
```

This migration works fine when I bypass the migration proxy via `mix ecto.migrate -r MyApp.Repo`, even if I run this after Electric has connected and created its tables.

However, if I instead try to run the migration through the proxy, it fails due to the existence of `electric.roles` and the fact that the proxy doesn't seem to default to the `public` schema like the normal repo's migrations do.

```
18:44:44.190 [info] create table roles
** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "roles" already exists
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.16.1) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.10.1) lib/ecto/migration/runner.ex:327: Ecto.Migration.Runner.log_and_execute_ddl/3
    (elixir 1.16.1) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.10.1) lib/ecto/migration/runner.ex:290: Ecto.Migration.Runner.perform_operation/3
    (stdlib 4.3.1.3) timer.erl:235: :timer.tc/1
    (ecto_sql 3.10.1) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/8
```

If I change my migration to the following it works.

```elixir
  def change do
    create table("public.roles") do
      add(:name, :string)

      timestamps()
    end
  end
```

**Comment by justindotpub** [comment]
It looks like I can get by all of the errors by changing the migrations to use `:roles` and then add the options `prefix: "public"`.  This was needed in `table`, `references` and `unique_index` calls.

**Comment by alco** [comment]
Postgres' default search path is `$user, public`. If your database role is named `electric`, that's what's causing the table name lookup to find `electric.roles` first.

Just use a different name for the DB role.

**Comment by justindotpub** [comment]
Ah, I see.  I misunderstood, thinking I was supposed to run the sync service with the electric role in my `DATABASE_URL`.  That fixes the issue.  Thank you.  🙏
